#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/ga73koz/zynq_work/xapp1167/sw/erode/xps_proj/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /ise_local2/umair_temp/14.5/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

PCWPRJFILE = data/ps7_system_prj.xml

FPGA_ARCH = zynq

DEVICE = xc7z020clg484-1

INTSTYLE = default

XPS_HDL_LANG = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error no

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

BRAMINIT_ELF_IMP_FILES =
BRAMINIT_ELF_IMP_FILE_ARGS =

BRAMINIT_ELF_SIM_FILES =
BRAMINIT_ELF_SIM_FILE_ARGS =

SIM_CMD = xterm -e ./isim_system

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s isim


CORE_STATE_DEVELOPMENT_FILES = /ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/family.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/family_support.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/coregen_comp_defs.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/common_types_pkg.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/proc_common_pkg.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/conv_funs_pkg.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_pkg.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/async_fifo_fg.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/sync_fifo_fg.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/basic_sfifo_fg.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/blk_mem_gen_wrapper.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/addsub.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/counter_bit.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/counter.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/direct_path_cntr.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/direct_path_cntr_ai.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/down_counter.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/eval_timer.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/inferred_lut4.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_steer.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_steer128.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_mirror128.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ld_arith_reg.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ld_arith_reg2.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/mux_onehot.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_bits.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_muxcy.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_gate.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_gate128.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_adder_bit.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_adder.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_counter_bit.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_counter.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_counter_top.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_occ_counter.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_occ_counter_top.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_dpram_select.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pselect.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pselect_mask.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl16_fifo.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo2.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo3.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_rbu.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/valid_be.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_with_enable_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/muxf_struct_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/cntr_incr_decr_addn_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/dynshreg_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/dynshreg_i_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/mux_onehot_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_rbu_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/compare_vectors_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pselect_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/counter_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_muxcy_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_gate_f.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/soft_reset.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/axi_lite_ipif_v1_01_a/hdl/vhdl/address_decoder.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/axi_lite_ipif_v1_01_a/hdl/vhdl/slave_attachment.vhd \
/ise_local2/umair_temp/14.5/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/axi_lite_ipif_v1_01_a/hdl/vhdl/axi_lite_ipif.vhd \
pcores/clk_detect_v1_00_a/hdl/vhdl/user_logic.vhd \
pcores/clk_detect_v1_00_a/hdl/vhdl/clk_detect.vhd \
pcores/image_filter_top_v1_04_a/synhdl/verilog/AXIvideo2Mat_32_1080_1920_16_s.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_k_buf_0_val_0.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/Erode_16_16_1080_1920_s.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_0_cols_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_0_cols_V_channel.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_0_data_stream_0_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_0_data_stream_1_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_0_data_stream_2_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_0_rows_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_0_rows_V_channel.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_1_cols_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_1_data_stream_0_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_1_data_stream_1_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_1_data_stream_2_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/FIFO_image_filter_img_1_rows_V.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/init.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/init_1.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/Mat2AXIvideo_32_1080_1920_16_s.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/image_filter.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/image_filter_ap_rst_if.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/image_filter_CONTROL_BUS_if.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/image_filter_INPUT_STREAM_if.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/image_filter_OUTPUT_STREAM_if.v \
pcores/image_filter_top_v1_04_a/synhdl/verilog/image_filter_top.v

WRAPPER_NGC_FILES = implementation/system_ps7_0_wrapper.ngc \
implementation/system_axi4_0_wrapper.ngc \
implementation/system_axi4_1_wrapper.ngc \
implementation/system_axi4_lite_wrapper.ngc \
implementation/system_clock_generator_0_wrapper.ngc \
implementation/system_proc_sys_reset_1_wrapper.ngc \
implementation/system_tpg_swrst_ff_wrapper.ngc \
implementation/system_tpg_swrst_wrapper.ngc \
implementation/system_filter_swrst_ff_wrapper.ngc \
implementation/system_filter_swrst_wrapper.ngc \
implementation/system_video_mux_0_wrapper.ngc \
implementation/system_clk_detect_0_wrapper.ngc \
implementation/system_vtc_0_wrapper.ngc \
implementation/system_hdmi_in_wrapper.ngc \
implementation/system_tpg_0_wrapper.ngc \
implementation/system_vid_in_axi4s_wrapper.ngc \
implementation/system_cresample_0_wrapper.ngc \
implementation/system_yuv2rgb_0_wrapper.ngc \
implementation/system_tpg_vdma_wrapper.ngc \
implementation/system_filter_engine_wrapper.ngc \
implementation/system_filter_vdma_wrapper.ngc \
implementation/system_logicvc_0_wrapper.ngc \
implementation/system_perf_mon_hp0_hp2_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = /nfs/TUEIEDAprojects/SystemDesign/work/zynq/umair-razzaq/xapp1167/sw/erode/xps_proj/etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = /nfs/TUEIEDAprojects/SystemDesign/work/zynq/umair-razzaq/xapp1167/sw/erode/xps_proj/SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF)
