############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 2013 Xilinx Inc. All rights reserved.
############################################################
open_project DCT_HLS_Project
set_top dct
add_files ../../project_documents/LabB/dct.cpp
add_files -tb ../../project_documents/LabB/dct_test.cpp
add_files -tb ../../project_documents/LabB/in.dat
add_files -tb ../../project_documents/LabB/out.golden.dat
open_solution "solution1"
set_part {xc7z020clg484-1}
create_clock -period 8 -name default
source "./DCT_HLS_Project/solution1/directives.tcl"
csim_design
csynth_design
cosim_design -trace_level none
export_design -format ip_catalog -description "An IP generated by Vivado HLS" -vendor "xilinx.com" -library "hls" -version "1.0"
