// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "borderInterpolate.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic borderInterpolate::ap_const_logic_1 = sc_dt::Log_1;
const bool borderInterpolate::ap_true = true;
const sc_lv<1> borderInterpolate::ap_const_lv1_0 = "0";
const sc_lv<32> borderInterpolate::ap_const_lv32_C = "1100";
const sc_lv<1> borderInterpolate::ap_const_lv1_1 = "1";
const sc_lv<5> borderInterpolate::ap_const_lv5_1 = "1";
const sc_lv<5> borderInterpolate::ap_const_lv5_2 = "10";
const sc_lv<5> borderInterpolate::ap_const_lv5_4 = "100";
const sc_lv<13> borderInterpolate::ap_const_lv13_1FFF = "1111111111111";
const sc_lv<5> borderInterpolate::ap_const_lv5_0 = "00000";
const sc_lv<13> borderInterpolate::ap_const_lv13_0 = "0000000000000";
const sc_lv<12> borderInterpolate::ap_const_lv12_1 = "1";
const sc_lv<14> borderInterpolate::ap_const_lv14_3FFE = "11111111111110";
const sc_lv<15> borderInterpolate::ap_const_lv15_0 = "000000000000000";
const sc_logic borderInterpolate::ap_const_logic_0 = sc_dt::Log_0;

borderInterpolate::borderInterpolate(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_ce );
    sensitive << ( sel_tmp30_reg_558 );
    sensitive << ( p_p2_cast1_cast_fu_379_p1 );
    sensitive << ( sel_tmp29_fu_395_p3 );

    SC_METHOD(thread_len_cast1_cast_fu_145_p1);
    sensitive << ( len_read_reg_409 );

    SC_METHOD(thread_len_cast1_fu_73_p1);
    sensitive << ( len );

    SC_METHOD(thread_or_cond_fu_87_p2);
    sensitive << ( tmp_1_fu_81_p2 );
    sensitive << ( rev_fu_67_p2 );

    SC_METHOD(thread_p_assign_1_fu_119_p2);
    sensitive << ( p );

    SC_METHOD(thread_p_assign_2_fu_205_p1);
    sensitive << ( or_cond_reg_438 );
    sensitive << ( tmp_13_fu_195_p2 );

    SC_METHOD(thread_p_assign_2_fu_205_p2);
    sensitive << ( tmp_12_cast_fu_191_p1 );
    sensitive << ( p_assign_2_fu_205_p1 );

    SC_METHOD(thread_p_assign_3_fu_131_p2);
    sensitive << ( p );

    SC_METHOD(thread_p_assign_4_fu_229_p2);
    sensitive << ( tmp_17_fu_223_p2 );
    sensitive << ( tmp_16_cast_cast_fu_219_p1 );

    SC_METHOD(thread_p_assign_fu_154_p3);
    sensitive << ( tmp_85_reg_450 );
    sensitive << ( tmp_4_fu_148_p2 );

    SC_METHOD(thread_p_p2_cast1_cast_fu_379_p1);
    sensitive << ( ap_reg_ppstg_p_p2_reg_478_pp0_it2 );

    SC_METHOD(thread_p_p2_cast_cast_fu_211_p1);
    sensitive << ( p_p2_reg_478 );

    SC_METHOD(thread_p_p2_fu_137_p3);
    sensitive << ( p );
    sensitive << ( tmp_85_fu_99_p3 );
    sensitive << ( p_assign_3_fu_131_p2 );

    SC_METHOD(thread_p_p3_fu_305_p3);
    sensitive << ( ap_reg_ppstg_p_read_reg_416_pp0_it1 );
    sensitive << ( ap_reg_ppstg_tmp_11_reg_473_pp0_it1 );

    SC_METHOD(thread_p_p_fu_170_p3);
    sensitive << ( p_read_reg_416 );
    sensitive << ( tmp_85_reg_450 );
    sensitive << ( p_assign_1_reg_468 );

    SC_METHOD(thread_rev_fu_67_p2);
    sensitive << ( tmp_fu_59_p3 );

    SC_METHOD(thread_sel_tmp10_fu_318_p2);
    sensitive << ( sel_tmp8_reg_516 );
    sensitive << ( sel_tmp9_reg_522 );

    SC_METHOD(thread_sel_tmp11_fu_322_p2);
    sensitive << ( ap_reg_ppstg_or_cond_reg_438_pp0_it1 );
    sensitive << ( sel_tmp2_reg_506 );

    SC_METHOD(thread_sel_tmp11_fu_322_p3);
    sensitive << ( p_assign_2_reg_501 );
    sensitive << ( sel_tmp10_fu_318_p2 );
    sensitive << ( sel_tmp11_fu_322_p2 );

    SC_METHOD(thread_sel_tmp16_demorgan_fu_291_p2);
    sensitive << ( tmp_5_reg_456 );
    sensitive << ( sel_tmp5_demorgan_fu_258_p2 );

    SC_METHOD(thread_sel_tmp18_demorgan_fu_329_p2);
    sensitive << ( ap_reg_ppstg_tmp_7_reg_462_pp0_it1 );
    sensitive << ( sel_tmp16_demorgan_reg_527 );

    SC_METHOD(thread_sel_tmp19_fu_333_p2);
    sensitive << ( ap_reg_ppstg_or_cond_reg_438_pp0_it1 );
    sensitive << ( p_p3_fu_305_p3 );

    SC_METHOD(thread_sel_tmp19_fu_333_p3);
    sensitive << ( sel_tmp18_demorgan_fu_329_p2 );
    sensitive << ( sel_tmp11_fu_322_p3 );
    sensitive << ( sel_tmp19_fu_333_p2 );

    SC_METHOD(thread_sel_tmp1_fu_245_p2);
    sensitive << ( tmp_2_reg_444 );
    sensitive << ( sel_tmp_fu_240_p2 );

    SC_METHOD(thread_sel_tmp20_fu_341_p1);
    sensitive << ( ap_reg_ppstg_p_read_reg_416_pp0_it1 );

    SC_METHOD(thread_sel_tmp20_fu_341_p3);
    sensitive << ( ap_reg_ppstg_or_cond_reg_438_pp0_it1 );
    sensitive << ( sel_tmp20_fu_341_p1 );
    sensitive << ( sel_tmp19_fu_333_p3 );

    SC_METHOD(thread_sel_tmp22_fu_348_p2);
    sensitive << ( tmp_6_reg_485 );
    sensitive << ( sel_tmp6_reg_511 );

    SC_METHOD(thread_sel_tmp23_fu_382_p3);
    sensitive << ( sel_tmp20_reg_538 );
    sensitive << ( sel_tmp22_reg_543 );

    SC_METHOD(thread_sel_tmp24_fu_352_p2);
    sensitive << ( tmp_9_reg_496 );
    sensitive << ( sel_tmp8_reg_516 );

    SC_METHOD(thread_sel_tmp25_fu_388_p1);
    sensitive << ( ap_reg_ppstg_p_p_reg_491_pp0_it2 );
    sensitive << ( sel_tmp28_reg_553 );
    sensitive << ( sel_tmp30_reg_558 );

    SC_METHOD(thread_sel_tmp25_fu_388_p3);
    sensitive << ( sel_tmp24_reg_548 );
    sensitive << ( sel_tmp25_fu_388_p1 );
    sensitive << ( sel_tmp23_fu_382_p3 );

    SC_METHOD(thread_sel_tmp26_fu_356_p2);
    sensitive << ( sel_tmp16_demorgan_reg_527 );

    SC_METHOD(thread_sel_tmp27_fu_361_p2);
    sensitive << ( ap_reg_ppstg_tmp_7_reg_462_pp0_it1 );
    sensitive << ( sel_tmp26_fu_356_p2 );

    SC_METHOD(thread_sel_tmp28_fu_366_p2);
    sensitive << ( tmp_6_reg_485 );
    sensitive << ( sel_tmp27_fu_361_p2 );

    SC_METHOD(thread_sel_tmp29_fu_395_p3);
    sensitive << ( sel_tmp28_reg_553 );
    sensitive << ( sel_tmp25_fu_388_p3 );

    SC_METHOD(thread_sel_tmp2_fu_250_p1);
    sensitive << ( or_cond_reg_438 );
    sensitive << ( p_assign_fu_154_p3 );

    SC_METHOD(thread_sel_tmp2_fu_250_p3);
    sensitive << ( sel_tmp1_fu_245_p2 );
    sensitive << ( sel_tmp2_fu_250_p1 );
    sensitive << ( p_assign_4_fu_229_p2 );

    SC_METHOD(thread_sel_tmp30_fu_371_p2);
    sensitive << ( tmp31_reg_533 );
    sensitive << ( sel_tmp27_fu_361_p2 );

    SC_METHOD(thread_sel_tmp5_demorgan_fu_258_p2);
    sensitive << ( or_cond_reg_438 );
    sensitive << ( tmp_2_reg_444 );

    SC_METHOD(thread_sel_tmp5_fu_262_p2);
    sensitive << ( sel_tmp5_demorgan_fu_258_p2 );

    SC_METHOD(thread_sel_tmp6_fu_268_p2);
    sensitive << ( tmp_5_reg_456 );
    sensitive << ( sel_tmp5_fu_262_p2 );

    SC_METHOD(thread_sel_tmp7_fu_273_p2);
    sensitive << ( tmp_6_fu_165_p2 );

    SC_METHOD(thread_sel_tmp8_fu_279_p2);
    sensitive << ( sel_tmp6_fu_268_p2 );
    sensitive << ( sel_tmp7_fu_273_p2 );

    SC_METHOD(thread_sel_tmp9_fu_285_p2);
    sensitive << ( tmp_9_fu_179_p2 );

    SC_METHOD(thread_sel_tmp_fu_240_p2);
    sensitive << ( tmp_reg_423 );
    sensitive << ( tmp_1_not_fu_235_p2 );

    SC_METHOD(thread_tmp31_fu_296_p2);
    sensitive << ( sel_tmp7_fu_273_p2 );
    sensitive << ( tmp_15_fu_214_p2 );

    SC_METHOD(thread_tmp_11_fu_125_p2);
    sensitive << ( borderType );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_12_cast_fu_191_p1);
    sensitive << ( tmp_12_fu_184_p3 );

    SC_METHOD(thread_tmp_12_fu_184_p3);
    sensitive << ( len_read_reg_409 );

    SC_METHOD(thread_tmp_13_fu_195_p2);
    sensitive << ( p_p_fu_170_p3 );

    SC_METHOD(thread_tmp_15_fu_214_p2);
    sensitive << ( ap_ce );
    sensitive << ( p_p2_reg_478 );
    sensitive << ( len_cast1_cast_fu_145_p1 );

    SC_METHOD(thread_tmp_16_cast_cast_fu_219_p1);
    sensitive << ( tmp_12_fu_184_p3 );

    SC_METHOD(thread_tmp_17_fu_223_p2);
    sensitive << ( p_p2_cast_cast_fu_211_p1 );

    SC_METHOD(thread_tmp_1_fu_81_p0);
    sensitive << ( p );

    SC_METHOD(thread_tmp_1_fu_81_p2);
    sensitive << ( ap_ce );
    sensitive << ( len_cast1_fu_73_p1 );
    sensitive << ( tmp_1_fu_81_p0 );

    SC_METHOD(thread_tmp_1_not_fu_235_p2);
    sensitive << ( tmp_1_reg_433 );

    SC_METHOD(thread_tmp_2_fu_93_p2);
    sensitive << ( borderType );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_4_fu_148_p2);
    sensitive << ( len_cast1_cast_fu_145_p1 );

    SC_METHOD(thread_tmp_5_fu_107_p2);
    sensitive << ( borderType );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_6_fu_165_p2);
    sensitive << ( len_read_reg_409 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_7_fu_113_p2);
    sensitive << ( borderType );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_85_fu_99_p3);
    sensitive << ( p );

    SC_METHOD(thread_tmp_9_fu_179_p0);
    sensitive << ( p_p_fu_170_p3 );

    SC_METHOD(thread_tmp_9_fu_179_p2);
    sensitive << ( ap_ce );
    sensitive << ( len_cast1_reg_428 );
    sensitive << ( tmp_9_fu_179_p0 );

    SC_METHOD(thread_tmp_fu_59_p3);
    sensitive << ( p );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "borderInterpolate_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, p, "(port)p");
    sc_trace(mVcdFile, len, "(port)len");
    sc_trace(mVcdFile, borderType, "(port)borderType");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
    sc_trace(mVcdFile, len_read_reg_409, "len_read_reg_409");
    sc_trace(mVcdFile, p_read_reg_416, "p_read_reg_416");
    sc_trace(mVcdFile, ap_reg_ppstg_p_read_reg_416_pp0_it1, "ap_reg_ppstg_p_read_reg_416_pp0_it1");
    sc_trace(mVcdFile, tmp_fu_59_p3, "tmp_fu_59_p3");
    sc_trace(mVcdFile, tmp_reg_423, "tmp_reg_423");
    sc_trace(mVcdFile, len_cast1_fu_73_p1, "len_cast1_fu_73_p1");
    sc_trace(mVcdFile, len_cast1_reg_428, "len_cast1_reg_428");
    sc_trace(mVcdFile, tmp_1_fu_81_p2, "tmp_1_fu_81_p2");
    sc_trace(mVcdFile, tmp_1_reg_433, "tmp_1_reg_433");
    sc_trace(mVcdFile, or_cond_fu_87_p2, "or_cond_fu_87_p2");
    sc_trace(mVcdFile, or_cond_reg_438, "or_cond_reg_438");
    sc_trace(mVcdFile, ap_reg_ppstg_or_cond_reg_438_pp0_it1, "ap_reg_ppstg_or_cond_reg_438_pp0_it1");
    sc_trace(mVcdFile, tmp_2_fu_93_p2, "tmp_2_fu_93_p2");
    sc_trace(mVcdFile, tmp_2_reg_444, "tmp_2_reg_444");
    sc_trace(mVcdFile, tmp_85_fu_99_p3, "tmp_85_fu_99_p3");
    sc_trace(mVcdFile, tmp_85_reg_450, "tmp_85_reg_450");
    sc_trace(mVcdFile, tmp_5_fu_107_p2, "tmp_5_fu_107_p2");
    sc_trace(mVcdFile, tmp_5_reg_456, "tmp_5_reg_456");
    sc_trace(mVcdFile, tmp_7_fu_113_p2, "tmp_7_fu_113_p2");
    sc_trace(mVcdFile, tmp_7_reg_462, "tmp_7_reg_462");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_7_reg_462_pp0_it1, "ap_reg_ppstg_tmp_7_reg_462_pp0_it1");
    sc_trace(mVcdFile, p_assign_1_fu_119_p2, "p_assign_1_fu_119_p2");
    sc_trace(mVcdFile, p_assign_1_reg_468, "p_assign_1_reg_468");
    sc_trace(mVcdFile, tmp_11_fu_125_p2, "tmp_11_fu_125_p2");
    sc_trace(mVcdFile, tmp_11_reg_473, "tmp_11_reg_473");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_11_reg_473_pp0_it1, "ap_reg_ppstg_tmp_11_reg_473_pp0_it1");
    sc_trace(mVcdFile, p_p2_fu_137_p3, "p_p2_fu_137_p3");
    sc_trace(mVcdFile, p_p2_reg_478, "p_p2_reg_478");
    sc_trace(mVcdFile, ap_reg_ppstg_p_p2_reg_478_pp0_it1, "ap_reg_ppstg_p_p2_reg_478_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_p_p2_reg_478_pp0_it2, "ap_reg_ppstg_p_p2_reg_478_pp0_it2");
    sc_trace(mVcdFile, tmp_6_fu_165_p2, "tmp_6_fu_165_p2");
    sc_trace(mVcdFile, tmp_6_reg_485, "tmp_6_reg_485");
    sc_trace(mVcdFile, p_p_fu_170_p3, "p_p_fu_170_p3");
    sc_trace(mVcdFile, p_p_reg_491, "p_p_reg_491");
    sc_trace(mVcdFile, ap_reg_ppstg_p_p_reg_491_pp0_it2, "ap_reg_ppstg_p_p_reg_491_pp0_it2");
    sc_trace(mVcdFile, tmp_9_fu_179_p2, "tmp_9_fu_179_p2");
    sc_trace(mVcdFile, tmp_9_reg_496, "tmp_9_reg_496");
    sc_trace(mVcdFile, p_assign_2_fu_205_p2, "p_assign_2_fu_205_p2");
    sc_trace(mVcdFile, p_assign_2_reg_501, "p_assign_2_reg_501");
    sc_trace(mVcdFile, sel_tmp2_fu_250_p3, "sel_tmp2_fu_250_p3");
    sc_trace(mVcdFile, sel_tmp2_reg_506, "sel_tmp2_reg_506");
    sc_trace(mVcdFile, sel_tmp6_fu_268_p2, "sel_tmp6_fu_268_p2");
    sc_trace(mVcdFile, sel_tmp6_reg_511, "sel_tmp6_reg_511");
    sc_trace(mVcdFile, sel_tmp8_fu_279_p2, "sel_tmp8_fu_279_p2");
    sc_trace(mVcdFile, sel_tmp8_reg_516, "sel_tmp8_reg_516");
    sc_trace(mVcdFile, sel_tmp9_fu_285_p2, "sel_tmp9_fu_285_p2");
    sc_trace(mVcdFile, sel_tmp9_reg_522, "sel_tmp9_reg_522");
    sc_trace(mVcdFile, sel_tmp16_demorgan_fu_291_p2, "sel_tmp16_demorgan_fu_291_p2");
    sc_trace(mVcdFile, sel_tmp16_demorgan_reg_527, "sel_tmp16_demorgan_reg_527");
    sc_trace(mVcdFile, tmp31_fu_296_p2, "tmp31_fu_296_p2");
    sc_trace(mVcdFile, tmp31_reg_533, "tmp31_reg_533");
    sc_trace(mVcdFile, sel_tmp20_fu_341_p3, "sel_tmp20_fu_341_p3");
    sc_trace(mVcdFile, sel_tmp20_reg_538, "sel_tmp20_reg_538");
    sc_trace(mVcdFile, sel_tmp22_fu_348_p2, "sel_tmp22_fu_348_p2");
    sc_trace(mVcdFile, sel_tmp22_reg_543, "sel_tmp22_reg_543");
    sc_trace(mVcdFile, sel_tmp24_fu_352_p2, "sel_tmp24_fu_352_p2");
    sc_trace(mVcdFile, sel_tmp24_reg_548, "sel_tmp24_reg_548");
    sc_trace(mVcdFile, sel_tmp28_fu_366_p2, "sel_tmp28_fu_366_p2");
    sc_trace(mVcdFile, sel_tmp28_reg_553, "sel_tmp28_reg_553");
    sc_trace(mVcdFile, sel_tmp30_fu_371_p2, "sel_tmp30_fu_371_p2");
    sc_trace(mVcdFile, sel_tmp30_reg_558, "sel_tmp30_reg_558");
    sc_trace(mVcdFile, tmp_1_fu_81_p0, "tmp_1_fu_81_p0");
    sc_trace(mVcdFile, rev_fu_67_p2, "rev_fu_67_p2");
    sc_trace(mVcdFile, p_assign_3_fu_131_p2, "p_assign_3_fu_131_p2");
    sc_trace(mVcdFile, len_cast1_cast_fu_145_p1, "len_cast1_cast_fu_145_p1");
    sc_trace(mVcdFile, tmp_4_fu_148_p2, "tmp_4_fu_148_p2");
    sc_trace(mVcdFile, p_assign_fu_154_p3, "p_assign_fu_154_p3");
    sc_trace(mVcdFile, tmp_9_fu_179_p0, "tmp_9_fu_179_p0");
    sc_trace(mVcdFile, tmp_12_fu_184_p3, "tmp_12_fu_184_p3");
    sc_trace(mVcdFile, tmp_13_fu_195_p2, "tmp_13_fu_195_p2");
    sc_trace(mVcdFile, tmp_12_cast_fu_191_p1, "tmp_12_cast_fu_191_p1");
    sc_trace(mVcdFile, p_assign_2_fu_205_p1, "p_assign_2_fu_205_p1");
    sc_trace(mVcdFile, p_p2_cast_cast_fu_211_p1, "p_p2_cast_cast_fu_211_p1");
    sc_trace(mVcdFile, tmp_17_fu_223_p2, "tmp_17_fu_223_p2");
    sc_trace(mVcdFile, tmp_16_cast_cast_fu_219_p1, "tmp_16_cast_cast_fu_219_p1");
    sc_trace(mVcdFile, tmp_1_not_fu_235_p2, "tmp_1_not_fu_235_p2");
    sc_trace(mVcdFile, sel_tmp_fu_240_p2, "sel_tmp_fu_240_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_245_p2, "sel_tmp1_fu_245_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_250_p1, "sel_tmp2_fu_250_p1");
    sc_trace(mVcdFile, p_assign_4_fu_229_p2, "p_assign_4_fu_229_p2");
    sc_trace(mVcdFile, sel_tmp5_demorgan_fu_258_p2, "sel_tmp5_demorgan_fu_258_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_262_p2, "sel_tmp5_fu_262_p2");
    sc_trace(mVcdFile, sel_tmp7_fu_273_p2, "sel_tmp7_fu_273_p2");
    sc_trace(mVcdFile, tmp_15_fu_214_p2, "tmp_15_fu_214_p2");
    sc_trace(mVcdFile, p_p3_fu_305_p3, "p_p3_fu_305_p3");
    sc_trace(mVcdFile, sel_tmp10_fu_318_p2, "sel_tmp10_fu_318_p2");
    sc_trace(mVcdFile, sel_tmp11_fu_322_p2, "sel_tmp11_fu_322_p2");
    sc_trace(mVcdFile, sel_tmp18_demorgan_fu_329_p2, "sel_tmp18_demorgan_fu_329_p2");
    sc_trace(mVcdFile, sel_tmp11_fu_322_p3, "sel_tmp11_fu_322_p3");
    sc_trace(mVcdFile, sel_tmp19_fu_333_p2, "sel_tmp19_fu_333_p2");
    sc_trace(mVcdFile, sel_tmp20_fu_341_p1, "sel_tmp20_fu_341_p1");
    sc_trace(mVcdFile, sel_tmp19_fu_333_p3, "sel_tmp19_fu_333_p3");
    sc_trace(mVcdFile, sel_tmp26_fu_356_p2, "sel_tmp26_fu_356_p2");
    sc_trace(mVcdFile, sel_tmp27_fu_361_p2, "sel_tmp27_fu_361_p2");
    sc_trace(mVcdFile, sel_tmp25_fu_388_p1, "sel_tmp25_fu_388_p1");
    sc_trace(mVcdFile, sel_tmp23_fu_382_p3, "sel_tmp23_fu_382_p3");
    sc_trace(mVcdFile, sel_tmp25_fu_388_p3, "sel_tmp25_fu_388_p3");
    sc_trace(mVcdFile, p_p2_cast1_cast_fu_379_p1, "p_p2_cast1_cast_fu_379_p1");
    sc_trace(mVcdFile, sel_tmp29_fu_395_p3, "sel_tmp29_fu_395_p3");

    }
}

borderInterpolate::~borderInterpolate() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void borderInterpolate::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read())) {
        ap_reg_ppstg_or_cond_reg_438_pp0_it1 = or_cond_reg_438.read();
        ap_reg_ppstg_p_p2_reg_478_pp0_it1 = p_p2_reg_478.read();
        ap_reg_ppstg_p_p2_reg_478_pp0_it2 = ap_reg_ppstg_p_p2_reg_478_pp0_it1.read();
        ap_reg_ppstg_p_p_reg_491_pp0_it2 = p_p_reg_491.read();
        ap_reg_ppstg_p_read_reg_416_pp0_it1 = p_read_reg_416.read();
        ap_reg_ppstg_tmp_11_reg_473_pp0_it1 = tmp_11_reg_473.read();
        ap_reg_ppstg_tmp_7_reg_462_pp0_it1 = tmp_7_reg_462.read();
        len_cast1_reg_428 = len_cast1_fu_73_p1.read();
        len_read_reg_409 = len.read();
        or_cond_reg_438 = or_cond_fu_87_p2.read();
        p_assign_1_reg_468 = p_assign_1_fu_119_p2.read();
        p_p2_reg_478 = p_p2_fu_137_p3.read();
        p_p_reg_491 = p_p_fu_170_p3.read();
        p_read_reg_416 = p.read();
        sel_tmp16_demorgan_reg_527 = sel_tmp16_demorgan_fu_291_p2.read();
        sel_tmp20_reg_538 = sel_tmp20_fu_341_p3.read();
        sel_tmp22_reg_543 = sel_tmp22_fu_348_p2.read();
        sel_tmp24_reg_548 = sel_tmp24_fu_352_p2.read();
        sel_tmp28_reg_553 = sel_tmp28_fu_366_p2.read();
        sel_tmp30_reg_558 = sel_tmp30_fu_371_p2.read();
        sel_tmp6_reg_511 = sel_tmp6_fu_268_p2.read();
        sel_tmp8_reg_516 = sel_tmp8_fu_279_p2.read();
        tmp31_reg_533 = tmp31_fu_296_p2.read();
        tmp_11_reg_473 = tmp_11_fu_125_p2.read();
        tmp_1_reg_433 = tmp_1_fu_81_p2.read();
        tmp_2_reg_444 = tmp_2_fu_93_p2.read();
        tmp_5_reg_456 = tmp_5_fu_107_p2.read();
        tmp_6_reg_485 = tmp_6_fu_165_p2.read();
        tmp_7_reg_462 = tmp_7_fu_113_p2.read();
        tmp_85_reg_450 = p.read().range(12, 12);
        tmp_9_reg_496 = tmp_9_fu_179_p2.read();
        tmp_reg_423 = p.read().range(12, 12);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read()) && esl_seteq<1,1,1>(or_cond_reg_438.read(), ap_const_lv1_0))) {
        p_assign_2_reg_501 = p_assign_2_fu_205_p2.read();
        sel_tmp2_reg_506 = sel_tmp2_fu_250_p3.read();
        sel_tmp9_reg_522 = sel_tmp9_fu_285_p2.read();
    }
}

void borderInterpolate::thread_ap_return() {
    ap_return = (!sel_tmp30_reg_558.read()[0].is_01())? sc_lv<15>(): ((sel_tmp30_reg_558.read()[0].to_bool())? p_p2_cast1_cast_fu_379_p1.read(): sel_tmp29_fu_395_p3.read());
}

void borderInterpolate::thread_len_cast1_cast_fu_145_p1() {
    len_cast1_cast_fu_145_p1 = esl_zext<13,12>(len_read_reg_409.read());
}

void borderInterpolate::thread_len_cast1_fu_73_p1() {
    len_cast1_fu_73_p1 = esl_zext<14,12>(len.read());
}

void borderInterpolate::thread_or_cond_fu_87_p2() {
    or_cond_fu_87_p2 = (tmp_1_fu_81_p2.read() & rev_fu_67_p2.read());
}

void borderInterpolate::thread_p_assign_1_fu_119_p2() {
    p_assign_1_fu_119_p2 = (p.read() ^ ap_const_lv13_1FFF);
}

void borderInterpolate::thread_p_assign_2_fu_205_p1() {
    p_assign_2_fu_205_p1 = esl_sext<15,13>(tmp_13_fu_195_p2.read());
}

void borderInterpolate::thread_p_assign_2_fu_205_p2() {
    p_assign_2_fu_205_p2 = (!tmp_12_cast_fu_191_p1.read().is_01() || !p_assign_2_fu_205_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(tmp_12_cast_fu_191_p1.read()) + sc_biguint<15>(p_assign_2_fu_205_p1.read()));
}

void borderInterpolate::thread_p_assign_3_fu_131_p2() {
    p_assign_3_fu_131_p2 = (!ap_const_lv13_0.is_01() || !p.read().is_01())? sc_lv<13>(): (sc_bigint<13>(ap_const_lv13_0) - sc_biguint<13>(p.read()));
}

void borderInterpolate::thread_p_assign_4_fu_229_p2() {
    p_assign_4_fu_229_p2 = (!tmp_17_fu_223_p2.read().is_01() || !tmp_16_cast_cast_fu_219_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(tmp_17_fu_223_p2.read()) + sc_biguint<14>(tmp_16_cast_cast_fu_219_p1.read()));
}

void borderInterpolate::thread_p_assign_fu_154_p3() {
    p_assign_fu_154_p3 = (!tmp_85_reg_450.read()[0].is_01())? sc_lv<13>(): ((tmp_85_reg_450.read()[0].to_bool())? ap_const_lv13_0: tmp_4_fu_148_p2.read());
}

void borderInterpolate::thread_p_p2_cast1_cast_fu_379_p1() {
    p_p2_cast1_cast_fu_379_p1 = esl_zext<15,13>(ap_reg_ppstg_p_p2_reg_478_pp0_it2.read());
}

void borderInterpolate::thread_p_p2_cast_cast_fu_211_p1() {
    p_p2_cast_cast_fu_211_p1 = esl_zext<14,13>(p_p2_reg_478.read());
}

void borderInterpolate::thread_p_p2_fu_137_p3() {
    p_p2_fu_137_p3 = (!tmp_85_fu_99_p3.read()[0].is_01())? sc_lv<13>(): ((tmp_85_fu_99_p3.read()[0].to_bool())? p_assign_3_fu_131_p2.read(): p.read());
}

void borderInterpolate::thread_p_p3_fu_305_p3() {
    p_p3_fu_305_p3 = (!ap_reg_ppstg_tmp_11_reg_473_pp0_it1.read()[0].is_01())? sc_lv<13>(): ((ap_reg_ppstg_tmp_11_reg_473_pp0_it1.read()[0].to_bool())? ap_const_lv13_1FFF: ap_reg_ppstg_p_read_reg_416_pp0_it1.read());
}

void borderInterpolate::thread_p_p_fu_170_p3() {
    p_p_fu_170_p3 = (!tmp_85_reg_450.read()[0].is_01())? sc_lv<13>(): ((tmp_85_reg_450.read()[0].to_bool())? p_assign_1_reg_468.read(): p_read_reg_416.read());
}

void borderInterpolate::thread_rev_fu_67_p2() {
    rev_fu_67_p2 = (tmp_fu_59_p3.read() ^ ap_const_lv1_1);
}

void borderInterpolate::thread_sel_tmp10_fu_318_p2() {
    sel_tmp10_fu_318_p2 = (sel_tmp8_reg_516.read() & sel_tmp9_reg_522.read());
}

void borderInterpolate::thread_sel_tmp11_fu_322_p2() {
    sel_tmp11_fu_322_p2 = esl_sext<15,14>(sel_tmp2_reg_506.read());
}

void borderInterpolate::thread_sel_tmp11_fu_322_p3() {
    sel_tmp11_fu_322_p3 = (!sel_tmp10_fu_318_p2.read()[0].is_01())? sc_lv<15>(): ((sel_tmp10_fu_318_p2.read()[0].to_bool())? p_assign_2_reg_501.read(): sel_tmp11_fu_322_p2.read());
}

void borderInterpolate::thread_sel_tmp16_demorgan_fu_291_p2() {
    sel_tmp16_demorgan_fu_291_p2 = (sel_tmp5_demorgan_fu_258_p2.read() | tmp_5_reg_456.read());
}

void borderInterpolate::thread_sel_tmp18_demorgan_fu_329_p2() {
    sel_tmp18_demorgan_fu_329_p2 = (sel_tmp16_demorgan_reg_527.read() | ap_reg_ppstg_tmp_7_reg_462_pp0_it1.read());
}

void borderInterpolate::thread_sel_tmp19_fu_333_p2() {
    sel_tmp19_fu_333_p2 = esl_sext<15,13>(p_p3_fu_305_p3.read());
}

void borderInterpolate::thread_sel_tmp19_fu_333_p3() {
    sel_tmp19_fu_333_p3 = (!sel_tmp18_demorgan_fu_329_p2.read()[0].is_01())? sc_lv<15>(): ((sel_tmp18_demorgan_fu_329_p2.read()[0].to_bool())? sel_tmp11_fu_322_p3.read(): sel_tmp19_fu_333_p2.read());
}

void borderInterpolate::thread_sel_tmp1_fu_245_p2() {
    sel_tmp1_fu_245_p2 = (tmp_2_reg_444.read() & sel_tmp_fu_240_p2.read());
}

void borderInterpolate::thread_sel_tmp20_fu_341_p1() {
    sel_tmp20_fu_341_p1 = esl_sext<15,13>(ap_reg_ppstg_p_read_reg_416_pp0_it1.read());
}

void borderInterpolate::thread_sel_tmp20_fu_341_p3() {
    sel_tmp20_fu_341_p3 = (!ap_reg_ppstg_or_cond_reg_438_pp0_it1.read()[0].is_01())? sc_lv<15>(): ((ap_reg_ppstg_or_cond_reg_438_pp0_it1.read()[0].to_bool())? sel_tmp20_fu_341_p1.read(): sel_tmp19_fu_333_p3.read());
}

void borderInterpolate::thread_sel_tmp22_fu_348_p2() {
    sel_tmp22_fu_348_p2 = (sel_tmp6_reg_511.read() & tmp_6_reg_485.read());
}

void borderInterpolate::thread_sel_tmp23_fu_382_p3() {
    sel_tmp23_fu_382_p3 = (!sel_tmp22_reg_543.read()[0].is_01())? sc_lv<15>(): ((sel_tmp22_reg_543.read()[0].to_bool())? ap_const_lv15_0: sel_tmp20_reg_538.read());
}

void borderInterpolate::thread_sel_tmp24_fu_352_p2() {
    sel_tmp24_fu_352_p2 = (sel_tmp8_reg_516.read() & tmp_9_reg_496.read());
}

void borderInterpolate::thread_sel_tmp25_fu_388_p1() {
    sel_tmp25_fu_388_p1 = esl_sext<15,13>(ap_reg_ppstg_p_p_reg_491_pp0_it2.read());
}

void borderInterpolate::thread_sel_tmp25_fu_388_p3() {
    sel_tmp25_fu_388_p3 = (!sel_tmp24_reg_548.read()[0].is_01())? sc_lv<15>(): ((sel_tmp24_reg_548.read()[0].to_bool())? sel_tmp25_fu_388_p1.read(): sel_tmp23_fu_382_p3.read());
}

void borderInterpolate::thread_sel_tmp26_fu_356_p2() {
    sel_tmp26_fu_356_p2 = (sel_tmp16_demorgan_reg_527.read() ^ ap_const_lv1_1);
}

void borderInterpolate::thread_sel_tmp27_fu_361_p2() {
    sel_tmp27_fu_361_p2 = (ap_reg_ppstg_tmp_7_reg_462_pp0_it1.read() & sel_tmp26_fu_356_p2.read());
}

void borderInterpolate::thread_sel_tmp28_fu_366_p2() {
    sel_tmp28_fu_366_p2 = (sel_tmp27_fu_361_p2.read() & tmp_6_reg_485.read());
}

void borderInterpolate::thread_sel_tmp29_fu_395_p3() {
    sel_tmp29_fu_395_p3 = (!sel_tmp28_reg_553.read()[0].is_01())? sc_lv<15>(): ((sel_tmp28_reg_553.read()[0].to_bool())? ap_const_lv15_0: sel_tmp25_fu_388_p3.read());
}

void borderInterpolate::thread_sel_tmp2_fu_250_p1() {
    sel_tmp2_fu_250_p1 = esl_sext<14,13>(p_assign_fu_154_p3.read());
}

void borderInterpolate::thread_sel_tmp2_fu_250_p3() {
    sel_tmp2_fu_250_p3 = (!sel_tmp1_fu_245_p2.read()[0].is_01())? sc_lv<14>(): ((sel_tmp1_fu_245_p2.read()[0].to_bool())? sel_tmp2_fu_250_p1.read(): p_assign_4_fu_229_p2.read());
}

void borderInterpolate::thread_sel_tmp30_fu_371_p2() {
    sel_tmp30_fu_371_p2 = (tmp31_reg_533.read() & sel_tmp27_fu_361_p2.read());
}

void borderInterpolate::thread_sel_tmp5_demorgan_fu_258_p2() {
    sel_tmp5_demorgan_fu_258_p2 = (or_cond_reg_438.read() | tmp_2_reg_444.read());
}

void borderInterpolate::thread_sel_tmp5_fu_262_p2() {
    sel_tmp5_fu_262_p2 = (sel_tmp5_demorgan_fu_258_p2.read() ^ ap_const_lv1_1);
}

void borderInterpolate::thread_sel_tmp6_fu_268_p2() {
    sel_tmp6_fu_268_p2 = (tmp_5_reg_456.read() & sel_tmp5_fu_262_p2.read());
}

void borderInterpolate::thread_sel_tmp7_fu_273_p2() {
    sel_tmp7_fu_273_p2 = (tmp_6_fu_165_p2.read() ^ ap_const_lv1_1);
}

void borderInterpolate::thread_sel_tmp8_fu_279_p2() {
    sel_tmp8_fu_279_p2 = (sel_tmp6_fu_268_p2.read() & sel_tmp7_fu_273_p2.read());
}

void borderInterpolate::thread_sel_tmp9_fu_285_p2() {
    sel_tmp9_fu_285_p2 = (tmp_9_fu_179_p2.read() ^ ap_const_lv1_1);
}

void borderInterpolate::thread_sel_tmp_fu_240_p2() {
    sel_tmp_fu_240_p2 = (tmp_reg_423.read() | tmp_1_not_fu_235_p2.read());
}

void borderInterpolate::thread_tmp31_fu_296_p2() {
    tmp31_fu_296_p2 = (tmp_15_fu_214_p2.read() & sel_tmp7_fu_273_p2.read());
}

void borderInterpolate::thread_tmp_11_fu_125_p2() {
    tmp_11_fu_125_p2 = (!borderType.read().is_01() || !ap_const_lv5_0.is_01())? sc_lv<1>(): sc_lv<1>(borderType.read() == ap_const_lv5_0);
}

void borderInterpolate::thread_tmp_12_cast_fu_191_p1() {
    tmp_12_cast_fu_191_p1 = esl_zext<15,13>(tmp_12_fu_184_p3.read());
}

void borderInterpolate::thread_tmp_12_fu_184_p3() {
    tmp_12_fu_184_p3 = esl_concat<12,1>(len_read_reg_409.read(), ap_const_lv1_0);
}

void borderInterpolate::thread_tmp_13_fu_195_p2() {
    tmp_13_fu_195_p2 = (p_p_fu_170_p3.read() ^ ap_const_lv13_1FFF);
}

void borderInterpolate::thread_tmp_15_fu_214_p2() {
    tmp_15_fu_214_p2 = (!p_p2_reg_478.read().is_01() || !len_cast1_cast_fu_145_p1.read().is_01())? sc_lv<1>(): (sc_biguint<13>(p_p2_reg_478.read()) < sc_biguint<13>(len_cast1_cast_fu_145_p1.read()));
}

void borderInterpolate::thread_tmp_16_cast_cast_fu_219_p1() {
    tmp_16_cast_cast_fu_219_p1 = esl_zext<14,13>(tmp_12_fu_184_p3.read());
}

void borderInterpolate::thread_tmp_17_fu_223_p2() {
    tmp_17_fu_223_p2 = (!ap_const_lv14_3FFE.is_01() || !p_p2_cast_cast_fu_211_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(ap_const_lv14_3FFE) - sc_biguint<14>(p_p2_cast_cast_fu_211_p1.read()));
}

void borderInterpolate::thread_tmp_1_fu_81_p0() {
    tmp_1_fu_81_p0 = esl_sext<14,13>(p.read());
}

void borderInterpolate::thread_tmp_1_fu_81_p2() {
    tmp_1_fu_81_p2 = (!tmp_1_fu_81_p0.read().is_01() || !len_cast1_fu_73_p1.read().is_01())? sc_lv<1>(): (sc_bigint<14>(tmp_1_fu_81_p0.read()) < sc_bigint<14>(len_cast1_fu_73_p1.read()));
}

void borderInterpolate::thread_tmp_1_not_fu_235_p2() {
    tmp_1_not_fu_235_p2 = (tmp_1_reg_433.read() ^ ap_const_lv1_1);
}

void borderInterpolate::thread_tmp_2_fu_93_p2() {
    tmp_2_fu_93_p2 = (!borderType.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<1>(): sc_lv<1>(borderType.read() == ap_const_lv5_1);
}

void borderInterpolate::thread_tmp_4_fu_148_p2() {
    tmp_4_fu_148_p2 = (!len_cast1_cast_fu_145_p1.read().is_01() || !ap_const_lv13_1FFF.is_01())? sc_lv<13>(): (sc_bigint<13>(len_cast1_cast_fu_145_p1.read()) + sc_biguint<13>(ap_const_lv13_1FFF));
}

void borderInterpolate::thread_tmp_5_fu_107_p2() {
    tmp_5_fu_107_p2 = (!borderType.read().is_01() || !ap_const_lv5_2.is_01())? sc_lv<1>(): sc_lv<1>(borderType.read() == ap_const_lv5_2);
}

void borderInterpolate::thread_tmp_6_fu_165_p2() {
    tmp_6_fu_165_p2 = (!len_read_reg_409.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<1>(): sc_lv<1>(len_read_reg_409.read() == ap_const_lv12_1);
}

void borderInterpolate::thread_tmp_7_fu_113_p2() {
    tmp_7_fu_113_p2 = (!borderType.read().is_01() || !ap_const_lv5_4.is_01())? sc_lv<1>(): sc_lv<1>(borderType.read() == ap_const_lv5_4);
}

void borderInterpolate::thread_tmp_85_fu_99_p3() {
    tmp_85_fu_99_p3 = p.read().range(12, 12);
}

void borderInterpolate::thread_tmp_9_fu_179_p0() {
    tmp_9_fu_179_p0 = esl_sext<14,13>(p_p_fu_170_p3.read());
}

void borderInterpolate::thread_tmp_9_fu_179_p2() {
    tmp_9_fu_179_p2 = (!tmp_9_fu_179_p0.read().is_01() || !len_cast1_reg_428.read().is_01())? sc_lv<1>(): (sc_bigint<14>(tmp_9_fu_179_p0.read()) < sc_bigint<14>(len_cast1_reg_428.read()));
}

void borderInterpolate::thread_tmp_fu_59_p3() {
    tmp_fu_59_p3 = p.read().range(12, 12);
}

}

