// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xerode_filter.h"

/************************** Function Implementation *************************/
int XErode_filter_Initialize(XErode_filter *InstancePtr, XErode_filter_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}

void XErode_filter_Start(XErode_filter *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XErode_filter_IsDone(XErode_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XErode_filter_IsIdle(XErode_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XErode_filter_IsReady(XErode_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XErode_filter_EnableAutoRestart(XErode_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XErode_filter_DisableAutoRestart(XErode_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XErode_filter_SetRows(XErode_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XErode_filter_GetRows(XErode_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XErode_filter_SetCols(XErode_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XErode_filter_GetCols(XErode_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XErode_filter_InterruptGlobalEnable(XErode_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_GIE, 1);
}

void XErode_filter_InterruptGlobalDisable(XErode_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_GIE, 0);
}

void XErode_filter_InterruptEnable(XErode_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_IER);
    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XErode_filter_InterruptDisable(XErode_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_IER);
    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XErode_filter_InterruptClear(XErode_filter *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XErode_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XErode_filter_InterruptGetEnabled(XErode_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_IER);
}

u32 XErode_filter_InterruptGetStatus(XErode_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XErode_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XERODE_FILTER_CONTROL_BUS_ADDR_ISR);
}

