// this is a template file which will be auto-generated by GRIP framework by using the IP-Xact description provided by this IP corresponding to Rule1 (Sobel filter + VDMA) 
// The IP supplier can then fill in this template to generate his driver targeting a specific platform

// for now it is simulated i.e it is a sample representation of the actual template file which doesnt contain all the registers of this IP


#include "SobelIP_Rule1Driver_template.h"



SobelIPRule1RegMap SobelIPRule1InitMode = {
											.AP_CTRL = {.offset = 0x00, .mask = 0x00000000, .value = 0xffffffff},
											.GIE = {.offset = 0x04, .mask = 0x00000000, .value = 0xffffffff},
											.IER = {.offset = 0x08, .mask = 0x00000000, .value = 0xffffffff},
											.ISR = {.offset = 0x0c, .mask = 0x00000000, .value = 0xffffffff},
											.ROWS_DATA = {.offset = 0x14, .mask = 0x00000000, .value = 0xffffffff},
											.COLS_DATA = {.offset = 0x1c, .mask = 0x00000000, .value = 0xffffffff}
									      };


SobelIPRule1RegMap SobelIPRule1StartMode = {
											.AP_CTRL = {.offset = 0x00, .mask = 0x00000000, .value = 0xffffffff},
											.GIE = {.offset = 0x04, .mask = 0x00000000, .value = 0xffffffff},
											.IER = {.offset = 0x08, .mask = 0x00000000, .value = 0xffffffff},
											.ISR = {.offset = 0x0c, .mask = 0x00000000, .value = 0xffffffff},
											.ROWS_DATA = {.offset = 0x14, .mask = 0x00000000, .value = 0xffffffff},
											.COLS_DATA = {.offset = 0x1c, .mask = 0x00000000, .value = 0xffffffff}
										   };


SobelIPRule1RegMap SobelIPRule1StopMode = {
											.AP_CTRL = {.offset = 0x00, .mask = 0x00000000, .value = 0xffffffff},
											.GIE = {.offset = 0x04, .mask = 0x00000000, .value = 0xffffffff},
											.IER = {.offset = 0x08, .mask = 0x00000000, .value = 0xffffffff},
											.ISR = {.offset = 0x0c, .mask = 0x00000000, .value = 0xffffffff},
											.ROWS_DATA = {.offset = 0x14, .mask = 0x00000000, .value = 0xffffffff},
											.COLS_DATA = {.offset = 0x1c, .mask = 0x00000000, .value = 0xffffffff}
										  };
												  


static void localWriteReg(unsigned int addr, unsigned int mask, unsigned int value) {
    // only write to reg if mask != 0
    if ((mask | 0x0) != 0x0) {
    *((volatile unsigned int *)(addr)) = (*(volatile unsigned int *)(addr) & ~(mask)) | value;
	}
}


static unsigned int localReadReg(unsigned int addr) {
    return (unsigned int) *((volatile unsigned int *)(addr));
}


// updates the Sobel IP peripheral's memory mapped registers with content provided in mode 
static void SetHAMode(SobelIPRule1RegMap mode, unsigned int baseaddr) {
	localWriteReg(baseaddr + mode.AP_CTRL.offset, mode.AP_CTRL.mask, mode.AP_CTRL.value);
	localWriteReg(baseaddr + mode.GIE.offset, mode.GIE.mask, mode.GIE.value);
	localWriteReg(baseaddr + mode.IER.offset, mode.IER.mask, mode.IER.value);
	localWriteReg(baseaddr + mode.ISR.offset, mode.ISR.mask, mode.ISR.value);
	localWriteReg(baseaddr + mode.ROWS_DATA.offset, mode.ROWS_DATA.mask, mode.ROWS_DATA.value);
	localWriteReg(baseaddr + mode.COLS_DATA.offset, mode.COLS_DATA.mask, mode.COLS_DATA.value);
}

// the IP supplier should make necessary modifications to initialize the Sobel IP here
void SobelIP_Rule1Driver_initialize(SobelIPRule1DriverInstance *InstancePtr) {
    // initializing the IP module
    SetHAMode(SobelIPRule1InitMode, InstancePtr->baseaddr);   

    // for this rule we also need to initialize the connected VDMA as well
    SOBELIP_VDMA_Driver_initialize(&InstancePtr->vdmaDriver);        
}


// the IP supplier should make necessary modifications to trigger the Sobel IP to start processing here
void SobelIP_Rule1Driver_start(SobelIPRule1DriverInstance *InstancePtr) {
    SetHAMode(SobelIPRule1StartMode, InstancePtr->baseaddr);
    
    SOBELIP_VDMA_Driver_start(&InstancePtr->vdmaDriver);
}


// the IP supplier should make necessary modifications to stop the Sobel IP processing here
void SobelIP_Rule1Driver_stop(SobelIPRule1DriverInstance *InstancePtr) {
	// stopping SobelIP
    SetHAMode(SobelIPRule1StopMode, InstancePtr->baseaddr);

	// stopping VDMA as well
	SOBELIP_VDMA_Driver_stop(&InstancePtr->vdmaDriver);
}

// the IP supplier should make necessary modifications to inform about the Busy status here
bool SobelIP_Rule1Driver_isBusy(SobelIPRule1DriverInstance *InstancePtr) {    
    return (bool) ((localReadReg(InstancePtr->baseaddr + SOBELIPRULE1_BUSY_STATUS_REG_offset) >> SOBELIPRULE1_BUSY_STATUS_REG_bit) & 1);
}





