-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2013.1
-- Copyright (C) 2013 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Erode_16_16_1080_1920_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    p_src_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    p_src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_0_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_0_V_read : OUT STD_LOGIC;
    p_src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_1_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_1_V_read : OUT STD_LOGIC;
    p_src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_2_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_2_V_read : OUT STD_LOGIC;
    p_dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_0_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_0_V_write : OUT STD_LOGIC;
    p_dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_1_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_1_V_write : OUT STD_LOGIC;
    p_dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_2_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_2_V_write : OUT STD_LOGIC );
end;


architecture behav of Erode_16_16_1080_1920_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_st6_fsm_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_ST_st7_fsm_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_ST_st8_fsm_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_ST_st9_fsm_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_sig_bdd_59 : BOOLEAN;
    signal i_2_fu_466_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_2_reg_1053 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp_i_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_i_reg_1058 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_i_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_i_reg_1069 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_i_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_i_reg_1077 : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_next1_i_fu_508_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_next1_i_reg_1088 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp2_i_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_i_reg_1093 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond7_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_i_fu_525_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_i_reg_1098 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_i_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_i_reg_1104 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_i_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_i_reg_1110 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_i_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_i_reg_1116 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_1122 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_i_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_i_reg_1129 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1134 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp5_reg_1140 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel2_i_fu_626_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel2_i_reg_1145 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_cond6_i_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_i_reg_1150 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_val13_5_i_fu_647_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val13_5_i_reg_1155 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel5_i_fu_661_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel5_i_reg_1160 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel8_i_fu_684_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel8_i_reg_1165 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel11_i_fu_707_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel11_i_reg_1170 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val26_5_i_fu_715_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val26_5_i_reg_1175 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel13_i_fu_729_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel13_i_reg_1180 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel16_i_fu_750_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel16_i_reg_1185 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel17_i_fu_758_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel17_i_reg_1190 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel3_i_fu_766_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_next_i_fu_778_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_next_i_reg_1203 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp28_i_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp28_i_reg_1208 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond8_i_fu_772_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_i_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_i_reg_1213 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp39_i_fu_828_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp39_i_reg_1218 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp41_i_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp41_i_reg_1224 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp43_i_fu_843_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp43_i_reg_1230 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond29_i_fu_848_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond29_i_reg_1236 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond30_i_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond30_i_reg_1243 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_fu_860_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_reg_1248 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp6_reg_1254 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_val26_1_i_fu_866_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val26_1_i_reg_1259 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel20_i_fu_901_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel20_i_reg_1264 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_cond35_i_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond35_i_reg_1269 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_val13_1_i_fu_922_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val13_1_i_reg_1274 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel23_i_fu_936_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel23_i_reg_1279 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel26_i_fu_959_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel26_i_reg_1284 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel29_i_fu_982_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel29_i_reg_1289 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel31_i_fu_997_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel31_i_reg_1294 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel34_i_fu_1018_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel34_i_reg_1299 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel35_i_fu_1026_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel35_i_reg_1304 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel21_i_fu_1034_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_idle : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_ready : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_empty_n : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_empty_n : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_empty_n : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_full_n : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_full_n : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_full_n : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write : STD_LOGIC;
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_0_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_1_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_2_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_0_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_1_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_2_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_0_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_1_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_2_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_rows : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_cols : STD_LOGIC_VECTOR (11 downto 0);
    signal temp_kernel_val_0_2_reg_70 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_kernel_val_1_0_reg_82 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_kernel_val_1_1_reg_94 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_kernel_val_0_1_reg_106 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_kernel_val_1_2_reg_118 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_kernel_val_2_0_reg_130 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_kernel_val_0_0_reg_142 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_kernel_val_2_1_reg_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_kernel_val_2_2_reg_166 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_reg_178 : STD_LOGIC_VECTOR (1 downto 0);
    signal result_val2_6_i_reg_190 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val13_6_i_reg_201 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val14_6_i_reg_212 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val16_6_i_reg_223 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val1520_6_i_reg_234 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val26_6_i_reg_245 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val_6_i_reg_256 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val27_6_i_reg_267 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val28_6_i_reg_278 : STD_LOGIC_VECTOR (7 downto 0);
    signal j_reg_289 : STD_LOGIC_VECTOR (1 downto 0);
    signal result_val2_2_i_reg_300 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val13_2_i_reg_312 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val14_2_i_reg_324 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val16_2_i_reg_336 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val1520_2_i_reg_348 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val26_2_i_reg_360 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val_2_i_reg_372 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val27_2_i_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_val28_2_i_reg_396 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_i_reg_408 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg : STD_LOGIC := '0';
    signal sel_tmp3_i_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_i_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_i_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_i_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_i_fu_536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_i_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_i_fu_569_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp16_i_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_i_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_i_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_i_fu_603_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_cond4_i_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel1_i_fu_614_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_cond5_i_fu_622_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_i_fu_640_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel4_i_fu_654_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel6_i_fu_669_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel7_i_fu_676_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel9_i_fu_692_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel10_i_fu_699_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel12_i_fu_722_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel14_i_fu_736_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel15_i_fu_743_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_45_fu_784_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp27_i_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp35_i_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp36_i_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp38_i_fu_822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp42_i_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp29_i_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond31_i_fu_874_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel18_i_fu_878_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_cond33_i_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel19_i_fu_889_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_cond34_i_fu_897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp44_i_fu_915_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel22_i_fu_929_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel24_i_fu_944_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel25_i_fu_951_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel27_i_fu_967_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel28_i_fu_974_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel30_i_fu_990_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel32_i_fu_1004_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel33_i_fu_1011_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);

    component filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_0_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_0_V_read : OUT STD_LOGIC;
        p_src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_1_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_1_V_read : OUT STD_LOGIC;
        p_src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_2_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_2_V_read : OUT STD_LOGIC;
        p_dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_0_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_0_V_write : OUT STD_LOGIC;
        p_dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_1_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_1_V_write : OUT STD_LOGIC;
        p_dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_2_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_2_V_write : OUT STD_LOGIC;
        kernel_val_0_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_0_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_0_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_1_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_1_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_1_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_2_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_2_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_2_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
        rows : IN STD_LOGIC_VECTOR (11 downto 0);
        cols : IN STD_LOGIC_VECTOR (11 downto 0) );
    end component;



begin
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420 : component filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start,
        ap_done => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done,
        ap_idle => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_idle,
        ap_ready => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_ready,
        p_src_data_stream_0_V_dout => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write,
        kernel_val_0_0_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_0_read,
        kernel_val_0_1_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_1_read,
        kernel_val_0_2_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_2_read,
        kernel_val_1_0_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_0_read,
        kernel_val_1_1_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_1_read,
        kernel_val_1_2_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_2_read,
        kernel_val_2_0_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_0_read,
        kernel_val_2_1_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_1_read,
        kernel_val_2_2_read => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_2_read,
        rows => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_rows,
        cols => grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_cols);




    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_done_reg assign process. --
    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_ST_st9_fsm_8 = ap_CS_fsm) and not((ap_const_logic_0 = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg assign process. --
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and not((exitcond_fu_460_p2 = ap_const_lv1_0)))) then 
                    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_ready)) then 
                    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg assign process. --
    ap_reg_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_ST_st2_fsm_1 = ap_CS_fsm)) then 
                i_2_reg_1053 <= i_2_fu_466_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                i_reg_178 <= i_2_reg_1053;
            elsif (((ap_ST_st1_fsm_0 = ap_CS_fsm) and not(ap_sig_bdd_59))) then 
                i_reg_178 <= ap_const_lv2_0;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                indvar_i_reg_408 <= ap_const_lv32_0;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                indvar_i_reg_408 <= indvar_next_i_reg_1203;
            end if; 
            if ((ap_ST_st3_fsm_2 = ap_CS_fsm)) then 
                indvar_next1_i_reg_1088 <= indvar_next1_i_fu_508_p2;
            end if; 
            if ((ap_ST_st6_fsm_5 = ap_CS_fsm)) then 
                indvar_next_i_reg_1203 <= indvar_next_i_fu_778_p2;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                j_reg_289 <= ap_const_lv2_0;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                j_reg_289 <= indvar_next1_i_reg_1088;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                newSel11_i_reg_1170 <= newSel11_i_fu_707_p3;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                newSel13_i_reg_1180 <= newSel13_i_fu_729_p3;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                newSel16_i_reg_1185 <= newSel16_i_fu_750_p3;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                newSel17_i_reg_1190 <= newSel17_i_fu_758_p3;
            end if; 
            if ((ap_ST_st7_fsm_6 = ap_CS_fsm)) then 
                newSel20_i_reg_1264 <= newSel20_i_fu_901_p3;
            end if; 
            if ((ap_ST_st7_fsm_6 = ap_CS_fsm)) then 
                newSel23_i_reg_1279 <= newSel23_i_fu_936_p3;
            end if; 
            if ((ap_ST_st7_fsm_6 = ap_CS_fsm)) then 
                newSel26_i_reg_1284 <= newSel26_i_fu_959_p3;
            end if; 
            if ((ap_ST_st7_fsm_6 = ap_CS_fsm)) then 
                newSel29_i_reg_1289 <= newSel29_i_fu_982_p3;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                newSel2_i_reg_1145 <= newSel2_i_fu_626_p3;
            end if; 
            if ((ap_ST_st7_fsm_6 = ap_CS_fsm)) then 
                newSel31_i_reg_1294 <= newSel31_i_fu_997_p3;
            end if; 
            if ((ap_ST_st7_fsm_6 = ap_CS_fsm)) then 
                newSel34_i_reg_1299 <= newSel34_i_fu_1018_p3;
            end if; 
            if ((ap_ST_st7_fsm_6 = ap_CS_fsm)) then 
                newSel35_i_reg_1304 <= newSel35_i_fu_1026_p3;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                newSel5_i_reg_1160 <= newSel5_i_fu_661_p3;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                newSel8_i_reg_1165 <= newSel8_i_fu_684_p3;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond7_fu_502_p2))) then 
                or_cond1_i_reg_1129 <= or_cond1_i_fu_587_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                or_cond29_i_reg_1236 <= or_cond29_i_fu_848_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                or_cond30_i_reg_1243 <= or_cond30_i_fu_854_p2;
            end if; 
            if ((ap_ST_st7_fsm_6 = ap_CS_fsm)) then 
                or_cond35_i_reg_1269 <= or_cond35_i_fu_909_p2;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                or_cond6_i_reg_1150 <= or_cond6_i_fu_634_p2;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond7_fu_502_p2))) then 
                or_cond_i_reg_1122 <= or_cond_i_fu_581_p2;
            end if; 
            if ((ap_ST_st7_fsm_6 = ap_CS_fsm)) then 
                result_val13_1_i_reg_1274 <= result_val13_1_i_fu_922_p3;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                result_val13_2_i_reg_312 <= result_val13_6_i_reg_201;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                result_val13_2_i_reg_312 <= result_val13_1_i_reg_1274;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                result_val13_5_i_reg_1155 <= result_val13_5_i_fu_647_p3;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                result_val13_6_i_reg_201 <= temp_kernel_val_1_0_reg_82;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                result_val13_6_i_reg_201 <= result_val13_5_i_reg_1155;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                result_val14_2_i_reg_324 <= result_val14_6_i_reg_212;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                result_val14_2_i_reg_324 <= newSel23_i_reg_1279;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                result_val14_6_i_reg_212 <= temp_kernel_val_1_1_reg_94;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                result_val14_6_i_reg_212 <= newSel5_i_reg_1160;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                result_val1520_2_i_reg_348 <= result_val1520_6_i_reg_234;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                result_val1520_2_i_reg_348 <= newSel29_i_reg_1289;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                result_val1520_6_i_reg_234 <= temp_kernel_val_1_2_reg_118;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                result_val1520_6_i_reg_234 <= newSel11_i_reg_1170;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                result_val16_2_i_reg_336 <= result_val16_6_i_reg_223;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                result_val16_2_i_reg_336 <= newSel26_i_reg_1284;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                result_val16_6_i_reg_223 <= temp_kernel_val_0_1_reg_106;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                result_val16_6_i_reg_223 <= newSel8_i_reg_1165;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                result_val26_1_i_reg_1259 <= result_val26_1_i_fu_866_p3;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                result_val26_2_i_reg_360 <= result_val26_6_i_reg_245;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                result_val26_2_i_reg_360 <= result_val26_1_i_reg_1259;
            end if; 
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then 
                result_val26_5_i_reg_1175 <= result_val26_5_i_fu_715_p3;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                result_val26_6_i_reg_245 <= temp_kernel_val_2_0_reg_130;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                result_val26_6_i_reg_245 <= result_val26_5_i_reg_1175;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                result_val27_2_i_reg_384 <= result_val27_6_i_reg_267;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                result_val27_2_i_reg_384 <= newSel34_i_reg_1299;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                result_val27_6_i_reg_267 <= temp_kernel_val_2_1_reg_154;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                result_val27_6_i_reg_267 <= newSel16_i_reg_1185;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                result_val28_2_i_reg_396 <= result_val28_6_i_reg_278;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                result_val28_2_i_reg_396 <= newSel35_i_reg_1304;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                result_val28_6_i_reg_278 <= temp_kernel_val_2_2_reg_166;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                result_val28_6_i_reg_278 <= newSel17_i_reg_1190;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                result_val2_2_i_reg_300 <= result_val2_6_i_reg_190;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                result_val2_2_i_reg_300 <= newSel21_i_fu_1034_p3;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                result_val2_6_i_reg_190 <= temp_kernel_val_0_2_reg_70;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                result_val2_6_i_reg_190 <= newSel3_i_fu_766_p3;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond7_fu_502_p2)))) then 
                result_val_2_i_reg_372 <= result_val_6_i_reg_256;
            elsif ((ap_ST_st8_fsm_7 = ap_CS_fsm)) then 
                result_val_2_i_reg_372 <= newSel31_i_reg_1294;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                result_val_6_i_reg_256 <= temp_kernel_val_0_0_reg_142;
            elsif ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                result_val_6_i_reg_256 <= newSel13_i_reg_1180;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond7_fu_502_p2))) then 
                sel_tmp13_i_reg_1104 <= sel_tmp13_i_fu_554_p2;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond7_fu_502_p2))) then 
                sel_tmp15_i_reg_1110 <= sel_tmp15_i_fu_559_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                sel_tmp28_i_reg_1208 <= sel_tmp28_i_fu_794_p2;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond7_fu_502_p2))) then 
                sel_tmp2_i_reg_1093 <= sel_tmp2_i_fu_520_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                sel_tmp32_i_reg_1213 <= sel_tmp32_i_fu_799_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                sel_tmp39_i_reg_1218 <= sel_tmp39_i_fu_828_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                sel_tmp41_i_reg_1224 <= sel_tmp41_i_fu_833_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                sel_tmp43_i_reg_1230 <= sel_tmp43_i_fu_843_p2;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                sel_tmp5_i_reg_1069 <= sel_tmp5_i_fu_490_p2;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond7_fu_502_p2))) then 
                sel_tmp6_i_reg_1098 <= sel_tmp6_i_fu_525_p2;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                sel_tmp8_i_reg_1077 <= sel_tmp8_i_fu_496_p2;
            end if; 
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_460_p2 = ap_const_lv1_0))) then 
                sel_tmp_i_reg_1058 <= sel_tmp_i_fu_472_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                temp_kernel_val_0_0_reg_142 <= result_val_2_i_reg_372;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                temp_kernel_val_0_1_reg_106 <= result_val16_2_i_reg_336;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                temp_kernel_val_0_2_reg_70 <= result_val2_2_i_reg_300;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                temp_kernel_val_1_0_reg_82 <= result_val13_2_i_reg_312;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                temp_kernel_val_1_1_reg_94 <= result_val14_2_i_reg_324;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                temp_kernel_val_1_2_reg_118 <= result_val1520_2_i_reg_348;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                temp_kernel_val_2_0_reg_130 <= result_val26_2_i_reg_360;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                temp_kernel_val_2_1_reg_154 <= result_val27_2_i_reg_384;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond8_i_fu_772_p2)))) then 
                temp_kernel_val_2_2_reg_166 <= result_val28_2_i_reg_396;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                tmp3_reg_1248 <= tmp3_fu_860_p2;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond7_fu_502_p2))) then 
                tmp5_reg_1140 <= grp_fu_456_p2;
            end if; 
            if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond8_i_fu_772_p2))) then 
                tmp6_reg_1254 <= grp_fu_456_p2;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond7_fu_502_p2))) then 
                tmp_2_i_reg_1116 <= tmp_2_i_fu_575_p2;
            end if; 
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond7_fu_502_p2))) then 
                tmp_reg_1134 <= tmp_fu_593_p2;
            end if; 
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm , ap_sig_bdd_59 , exitcond_fu_460_p2 , exitcond7_fu_502_p2 , exitcond8_i_fu_772_p2 , grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_bdd_59)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if ((exitcond_fu_460_p2 = ap_const_lv1_0)) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_st9_fsm_8;
                end if;
            when ap_ST_st3_fsm_2 => 
                if (not((ap_const_lv1_0 = exitcond7_fu_502_p2))) then
                    ap_NS_fsm <= ap_ST_st6_fsm_5;
                else
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                end if;
            when ap_ST_st4_fsm_3 => 
                ap_NS_fsm <= ap_ST_st5_fsm_4;
            when ap_ST_st5_fsm_4 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when ap_ST_st6_fsm_5 => 
                if ((ap_const_lv1_0 = exitcond8_i_fu_772_p2)) then
                    ap_NS_fsm <= ap_ST_st7_fsm_6;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when ap_ST_st7_fsm_6 => 
                ap_NS_fsm <= ap_ST_st8_fsm_7;
            when ap_ST_st8_fsm_7 => 
                ap_NS_fsm <= ap_ST_st6_fsm_5;
            when ap_ST_st9_fsm_8 => 
                if (not((ap_const_logic_0 = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_st9_fsm_8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm, grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_ST_st9_fsm_8 = ap_CS_fsm) and not((ap_const_logic_0 = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_CS_fsm)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_ST_st1_fsm_0 = ap_CS_fsm))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_CS_fsm, grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)
    begin
        if (((ap_ST_st9_fsm_8 = ap_CS_fsm) and not((ap_const_logic_0 = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_bdd_59 assign process. --
    ap_sig_bdd_59_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_bdd_59 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

    exitcond7_fu_502_p2 <= "1" when (j_reg_289 = ap_const_lv2_3) else "0";
    exitcond8_i_fu_772_p2 <= "1" when (indvar_i_reg_408 = ap_const_lv32_0) else "0";
    exitcond_fu_460_p2 <= "1" when (i_reg_178 = ap_const_lv2_3) else "0";
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_cols <= p_src_cols_V_read;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_0_read <= temp_kernel_val_0_0_reg_142;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_1_read <= temp_kernel_val_0_1_reg_106;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_2_read <= temp_kernel_val_0_2_reg_70;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_0_read <= temp_kernel_val_1_0_reg_82;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_1_read <= temp_kernel_val_1_1_reg_94;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_2_read <= temp_kernel_val_1_2_reg_118;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_0_read <= temp_kernel_val_2_0_reg_130;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_1_read <= temp_kernel_val_2_1_reg_154;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_2_read <= temp_kernel_val_2_2_reg_166;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_full_n <= p_dst_data_stream_0_V_full_n;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_full_n <= p_dst_data_stream_1_V_full_n;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_full_n <= p_dst_data_stream_2_V_full_n;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_dout <= p_src_data_stream_0_V_dout;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_empty_n <= p_src_data_stream_0_V_empty_n;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_dout <= p_src_data_stream_1_V_dout;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_empty_n <= p_src_data_stream_1_V_empty_n;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_dout <= p_src_data_stream_2_V_dout;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_empty_n <= p_src_data_stream_2_V_empty_n;
    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_rows <= p_src_rows_V_read;
    grp_fu_456_p2 <= (sel_tmp_i_reg_1058 or sel_tmp8_i_reg_1077);
    i_2_fu_466_p2 <= std_logic_vector(unsigned(i_reg_178) + unsigned(ap_const_lv2_1));
    indvar_next1_i_fu_508_p2 <= std_logic_vector(unsigned(j_reg_289) + unsigned(ap_const_lv2_1));
    indvar_next_i_fu_778_p2 <= std_logic_vector(unsigned(indvar_i_reg_408) + unsigned(ap_const_lv32_1));
    newSel10_i_fu_699_p3 <= 
        newSel9_i_fu_692_p3 when (or_cond2_i_fu_599_p2(0) = '1') else 
        result_val1520_6_i_reg_234;
    newSel11_i_fu_707_p3 <= 
        result_val1520_6_i_reg_234 when (or_cond4_i_fu_610_p2(0) = '1') else 
        newSel10_i_fu_699_p3;
    newSel12_i_fu_722_p3 <= 
        ap_const_lv8_1 when (tmp_2_i_reg_1116(0) = '1') else 
        result_val_6_i_reg_256;
    newSel13_i_fu_729_p3 <= 
        result_val_6_i_reg_256 when (or_cond_i_reg_1122(0) = '1') else 
        newSel12_i_fu_722_p3;
    newSel14_i_fu_736_p3 <= 
        result_val27_6_i_reg_267 when (tmp_2_i_reg_1116(0) = '1') else 
        ap_const_lv8_1;
    newSel15_i_fu_743_p3 <= 
        result_val27_6_i_reg_267 when (or_cond_i_reg_1122(0) = '1') else 
        newSel14_i_fu_736_p3;
    newSel16_i_fu_750_p3 <= 
        newSel15_i_fu_743_p3 when (or_cond4_i_fu_610_p2(0) = '1') else 
        result_val27_6_i_reg_267;
    newSel17_i_fu_758_p3 <= 
        result_val28_6_i_reg_278 when (or_cond6_i_fu_634_p2(0) = '1') else 
        ap_const_lv8_1;
    newSel18_i_fu_878_p3 <= 
        result_val2_2_i_reg_300 when (sel_tmp39_i_reg_1218(0) = '1') else 
        ap_const_lv8_0;
    newSel19_i_fu_889_p3 <= 
        result_val2_2_i_reg_300 when (or_cond31_i_fu_874_p2(0) = '1') else 
        newSel18_i_fu_878_p3;
    newSel1_i_fu_614_p3 <= 
        result_val2_6_i_reg_190 when (or_cond2_i_fu_599_p2(0) = '1') else 
        newSel_i_fu_603_p3;
    newSel20_i_fu_901_p3 <= 
        result_val2_2_i_reg_300 when (or_cond33_i_fu_885_p2(0) = '1') else 
        newSel19_i_fu_889_p3;
    newSel21_i_fu_1034_p3 <= 
        newSel20_i_reg_1264 when (or_cond35_i_reg_1269(0) = '1') else 
        result_val2_2_i_reg_300;
    newSel22_i_fu_929_p3 <= 
        ap_const_lv8_0 when (sel_tmp41_i_reg_1224(0) = '1') else 
        result_val14_2_i_reg_324;
    newSel23_i_fu_936_p3 <= 
        result_val14_2_i_reg_324 when (or_cond33_i_fu_885_p2(0) = '1') else 
        newSel22_i_fu_929_p3;
    newSel24_i_fu_944_p3 <= 
        ap_const_lv8_0 when (sel_tmp39_i_reg_1218(0) = '1') else 
        result_val16_2_i_reg_336;
    newSel25_i_fu_951_p3 <= 
        result_val16_2_i_reg_336 when (or_cond31_i_fu_874_p2(0) = '1') else 
        newSel24_i_fu_944_p3;
    newSel26_i_fu_959_p3 <= 
        result_val16_2_i_reg_336 when (or_cond33_i_fu_885_p2(0) = '1') else 
        newSel25_i_fu_951_p3;
    newSel27_i_fu_967_p3 <= 
        result_val1520_2_i_reg_348 when (sel_tmp41_i_reg_1224(0) = '1') else 
        ap_const_lv8_0;
    newSel28_i_fu_974_p3 <= 
        newSel27_i_fu_967_p3 when (or_cond31_i_fu_874_p2(0) = '1') else 
        result_val1520_2_i_reg_348;
    newSel29_i_fu_982_p3 <= 
        result_val1520_2_i_reg_348 when (or_cond33_i_fu_885_p2(0) = '1') else 
        newSel28_i_fu_974_p3;
    newSel2_i_fu_626_p3 <= 
        result_val2_6_i_reg_190 when (or_cond4_i_fu_610_p2(0) = '1') else 
        newSel1_i_fu_614_p3;
    newSel30_i_fu_990_p3 <= 
        ap_const_lv8_0 when (sel_tmp43_i_reg_1230(0) = '1') else 
        result_val_2_i_reg_372;
    newSel31_i_fu_997_p3 <= 
        result_val_2_i_reg_372 when (or_cond29_i_reg_1236(0) = '1') else 
        newSel30_i_fu_990_p3;
    newSel32_i_fu_1004_p3 <= 
        result_val27_2_i_reg_384 when (sel_tmp43_i_reg_1230(0) = '1') else 
        ap_const_lv8_0;
    newSel33_i_fu_1011_p3 <= 
        result_val27_2_i_reg_384 when (or_cond29_i_reg_1236(0) = '1') else 
        newSel32_i_fu_1004_p3;
    newSel34_i_fu_1018_p3 <= 
        newSel33_i_fu_1011_p3 when (or_cond33_i_fu_885_p2(0) = '1') else 
        result_val27_2_i_reg_384;
    newSel35_i_fu_1026_p3 <= 
        result_val28_2_i_reg_396 when (or_cond35_i_fu_909_p2(0) = '1') else 
        ap_const_lv8_0;
    newSel3_i_fu_766_p3 <= 
        newSel2_i_reg_1145 when (or_cond6_i_reg_1150(0) = '1') else 
        result_val2_6_i_reg_190;
    newSel4_i_fu_654_p3 <= 
        ap_const_lv8_1 when (sel_tmp15_i_reg_1110(0) = '1') else 
        result_val14_6_i_reg_212;
    newSel5_i_fu_661_p3 <= 
        result_val14_6_i_reg_212 when (or_cond4_i_fu_610_p2(0) = '1') else 
        newSel4_i_fu_654_p3;
    newSel6_i_fu_669_p3 <= 
        ap_const_lv8_1 when (sel_tmp13_i_reg_1104(0) = '1') else 
        result_val16_6_i_reg_223;
    newSel7_i_fu_676_p3 <= 
        result_val16_6_i_reg_223 when (or_cond2_i_fu_599_p2(0) = '1') else 
        newSel6_i_fu_669_p3;
    newSel8_i_fu_684_p3 <= 
        result_val16_6_i_reg_223 when (or_cond4_i_fu_610_p2(0) = '1') else 
        newSel7_i_fu_676_p3;
    newSel9_i_fu_692_p3 <= 
        result_val1520_6_i_reg_234 when (sel_tmp15_i_reg_1110(0) = '1') else 
        ap_const_lv8_1;
    newSel_i_fu_603_p3 <= 
        result_val2_6_i_reg_190 when (sel_tmp13_i_reg_1104(0) = '1') else 
        ap_const_lv8_1;
    or_cond1_i_fu_587_p2 <= (tmp_2_i_fu_575_p2 or sel_tmp16_i_fu_564_p2);
    or_cond29_i_fu_848_p2 <= (sel_tmp32_i_fu_799_p2 or sel_tmp28_i_fu_794_p2);
    or_cond2_i_fu_599_p2 <= (sel_tmp_i_reg_1058 and tmp_reg_1134);
    or_cond30_i_fu_854_p2 <= (sel_tmp43_i_fu_843_p2 or sel_tmp42_i_fu_838_p2);
    or_cond31_i_fu_874_p2 <= (sel_tmp_i_reg_1058 and tmp3_reg_1248);
    or_cond33_i_fu_885_p2 <= (or_cond29_i_reg_1236 or or_cond30_i_reg_1243);
    or_cond34_i_fu_897_p2 <= (tmp3_reg_1248 and tmp6_reg_1254);
    or_cond35_i_fu_909_p2 <= (or_cond33_i_fu_885_p2 or or_cond34_i_fu_897_p2);
    or_cond4_i_fu_610_p2 <= (or_cond_i_reg_1122 or or_cond1_i_reg_1129);
    or_cond5_i_fu_622_p2 <= (tmp_reg_1134 and tmp5_reg_1140);
    or_cond6_i_fu_634_p2 <= (or_cond4_i_fu_610_p2 or or_cond5_i_fu_622_p2);
    or_cond_i_fu_581_p2 <= (sel_tmp6_i_fu_525_p2 or sel_tmp2_i_fu_520_p2);
    p_dst_data_stream_0_V_din <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_din;

    -- p_dst_data_stream_0_V_write assign process. --
    p_dst_data_stream_0_V_write_assign_proc : process(ap_CS_fsm, grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st9_fsm_8 = ap_CS_fsm))) then 
            p_dst_data_stream_0_V_write <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write;
        else 
            p_dst_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_dst_data_stream_1_V_din <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_din;

    -- p_dst_data_stream_1_V_write assign process. --
    p_dst_data_stream_1_V_write_assign_proc : process(ap_CS_fsm, grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st9_fsm_8 = ap_CS_fsm))) then 
            p_dst_data_stream_1_V_write <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write;
        else 
            p_dst_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_dst_data_stream_2_V_din <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_din;

    -- p_dst_data_stream_2_V_write assign process. --
    p_dst_data_stream_2_V_write_assign_proc : process(ap_CS_fsm, grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st9_fsm_8 = ap_CS_fsm))) then 
            p_dst_data_stream_2_V_write <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write;
        else 
            p_dst_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    -- p_src_data_stream_0_V_read assign process. --
    p_src_data_stream_0_V_read_assign_proc : process(ap_CS_fsm, grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st9_fsm_8 = ap_CS_fsm))) then 
            p_src_data_stream_0_V_read <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read;
        else 
            p_src_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- p_src_data_stream_1_V_read assign process. --
    p_src_data_stream_1_V_read_assign_proc : process(ap_CS_fsm, grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st9_fsm_8 = ap_CS_fsm))) then 
            p_src_data_stream_1_V_read <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read;
        else 
            p_src_data_stream_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- p_src_data_stream_2_V_read assign process. --
    p_src_data_stream_2_V_read_assign_proc : process(ap_CS_fsm, grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st9_fsm_8 = ap_CS_fsm))) then 
            p_src_data_stream_2_V_read <= grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read;
        else 
            p_src_data_stream_2_V_read <= ap_const_logic_0;
        end if; 
    end process;

    result_val13_1_i_fu_922_p3 <= 
        result_val13_2_i_reg_312 when (sel_tmp32_i_reg_1213(0) = '1') else 
        sel_tmp44_i_fu_915_p3;
    result_val13_5_i_fu_647_p3 <= 
        result_val13_6_i_reg_201 when (sel_tmp6_i_reg_1098(0) = '1') else 
        sel_tmp17_i_fu_640_p3;
    result_val26_1_i_fu_866_p3 <= 
        ap_const_lv8_0 when (sel_tmp32_i_fu_799_p2(0) = '1') else 
        result_val26_2_i_reg_360;
    result_val26_5_i_fu_715_p3 <= 
        ap_const_lv8_1 when (sel_tmp6_i_reg_1098(0) = '1') else 
        result_val26_6_i_reg_245;
    sel_tmp10_i_fu_536_p2 <= "0" when (j_reg_289 = ap_const_lv2_1) else "1";
    sel_tmp12_i_fu_548_p2 <= "1" when (j_reg_289 = ap_const_lv2_1) else "0";
    sel_tmp13_i_fu_554_p2 <= (sel_tmp8_i_reg_1077 and sel_tmp12_i_fu_548_p2);
    sel_tmp15_i_fu_559_p2 <= (sel_tmp_i_reg_1058 and sel_tmp12_i_fu_548_p2);
    sel_tmp16_i_fu_564_p2 <= (sel_tmp5_i_reg_1069 and sel_tmp12_i_fu_548_p2);
    sel_tmp17_i_fu_640_p3 <= 
        ap_const_lv8_1 when (sel_tmp2_i_reg_1093(0) = '1') else 
        result_val13_6_i_reg_201;
    sel_tmp1_i_fu_514_p2 <= "1" when (j_reg_289 = ap_const_lv2_0) else "0";
    sel_tmp27_i_fu_788_p2 <= "1" when (tmp_45_fu_784_p1 = ap_const_lv2_1) else "0";
    sel_tmp28_i_fu_794_p2 <= (sel_tmp_i_reg_1058 and sel_tmp27_i_fu_788_p2);
    sel_tmp2_i_fu_520_p2 <= (sel_tmp_i_reg_1058 and sel_tmp1_i_fu_514_p2);
    sel_tmp32_i_fu_799_p2 <= (sel_tmp5_i_reg_1069 and sel_tmp27_i_fu_788_p2);
    sel_tmp35_i_fu_804_p2 <= "0" when (tmp_45_fu_784_p1 = ap_const_lv2_1) else "1";
    sel_tmp36_i_fu_810_p2 <= "0" when (tmp_45_fu_784_p1 = ap_const_lv2_2) else "1";
    sel_tmp38_i_fu_822_p2 <= "1" when (tmp_45_fu_784_p1 = ap_const_lv2_2) else "0";
    sel_tmp39_i_fu_828_p2 <= (sel_tmp8_i_reg_1077 and sel_tmp38_i_fu_822_p2);
    sel_tmp3_i_fu_478_p2 <= "0" when (i_reg_178 = ap_const_lv2_0) else "1";
    sel_tmp41_i_fu_833_p2 <= (sel_tmp_i_reg_1058 and sel_tmp38_i_fu_822_p2);
    sel_tmp42_i_fu_838_p2 <= (sel_tmp5_i_reg_1069 and sel_tmp38_i_fu_822_p2);
    sel_tmp43_i_fu_843_p2 <= (sel_tmp8_i_reg_1077 and sel_tmp27_i_fu_788_p2);
    sel_tmp44_i_fu_915_p3 <= 
        ap_const_lv8_0 when (sel_tmp28_i_reg_1208(0) = '1') else 
        result_val13_2_i_reg_312;
    sel_tmp4_i_fu_484_p2 <= "0" when (i_reg_178 = ap_const_lv2_1) else "1";
    sel_tmp5_i_fu_490_p2 <= (sel_tmp3_i_fu_478_p2 and sel_tmp4_i_fu_484_p2);
    sel_tmp6_i_fu_525_p2 <= (sel_tmp5_i_reg_1069 and sel_tmp1_i_fu_514_p2);
    sel_tmp8_i_fu_496_p2 <= "1" when (i_reg_178 = ap_const_lv2_0) else "0";
    sel_tmp9_i_fu_530_p2 <= "0" when (j_reg_289 = ap_const_lv2_0) else "1";
    sel_tmp_i_fu_472_p2 <= "1" when (i_reg_178 = ap_const_lv2_1) else "0";
    tmp1_i_fu_542_p2 <= (sel_tmp9_i_fu_530_p2 and sel_tmp10_i_fu_536_p2);
    tmp29_i_fu_816_p2 <= (sel_tmp35_i_fu_804_p2 and sel_tmp36_i_fu_810_p2);
    tmp3_fu_860_p2 <= (tmp29_i_fu_816_p2 or sel_tmp38_i_fu_822_p2);
    tmp_1_i_fu_569_p2 <= (i_reg_178 or j_reg_289);
    tmp_2_i_fu_575_p2 <= "1" when (tmp_1_i_fu_569_p2 = ap_const_lv2_0) else "0";
    tmp_45_fu_784_p1 <= indvar_i_reg_408(2 - 1 downto 0);
    tmp_fu_593_p2 <= (tmp1_i_fu_542_p2 or sel_tmp12_i_fu_548_p2);
end behav;
