// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _dct_HH_
#define _dct_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "read_data.h"
#include "dct_Loop_Row_DCT_Loop_proc.h"
#include "dct_Loop_Xpose_Row_Outer_Loop_proc.h"
#include "dct_Loop_Col_DCT_Loop_proc.h"
#include "dct_Loop_Xpose_Col_Outer_Loop_proc.h"
#include "write_data.h"
#include "dct_buf_2d_in.h"
#include "dct_row_outbuf.h"

namespace ap_rtl {

struct dct : public sc_module {
    // Port declarations 26
    sc_out< sc_lv<6> > input_r_address0;
    sc_out< sc_logic > input_r_ce0;
    sc_out< sc_lv<16> > input_r_d0;
    sc_in< sc_lv<16> > input_r_q0;
    sc_out< sc_logic > input_r_we0;
    sc_out< sc_lv<6> > input_r_address1;
    sc_out< sc_logic > input_r_ce1;
    sc_out< sc_lv<16> > input_r_d1;
    sc_in< sc_lv<16> > input_r_q1;
    sc_out< sc_logic > input_r_we1;
    sc_out< sc_lv<6> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_lv<16> > output_r_d0;
    sc_in< sc_lv<16> > output_r_q0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<6> > output_r_address1;
    sc_out< sc_logic > output_r_ce1;
    sc_out< sc_lv<16> > output_r_d1;
    sc_in< sc_lv<16> > output_r_q1;
    sc_out< sc_logic > output_r_we1;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;


    // Module declarations
    dct(sc_module_name name);
    SC_HAS_PROCESS(dct);

    ~dct();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    read_data* read_data_U0;
    dct_Loop_Row_DCT_Loop_proc* dct_Loop_Row_DCT_Loop_proc_U0;
    dct_Loop_Xpose_Row_Outer_Loop_proc* dct_Loop_Xpose_Row_Outer_Loop_proc_U0;
    dct_Loop_Col_DCT_Loop_proc* dct_Loop_Col_DCT_Loop_proc_U0;
    dct_Loop_Xpose_Col_Outer_Loop_proc* dct_Loop_Xpose_Col_Outer_Loop_proc_U0;
    write_data* write_data_U0;
    dct_buf_2d_in* buf_2d_in_U;
    dct_row_outbuf* row_outbuf_U;
    dct_buf_2d_in* col_inbuf_U;
    dct_row_outbuf* col_outbuf_U;
    dct_row_outbuf* buf_2d_out_U;
    sc_signal< sc_logic > read_data_U0_ap_start;
    sc_signal< sc_logic > read_data_U0_ap_done;
    sc_signal< sc_logic > read_data_U0_ap_continue;
    sc_signal< sc_logic > read_data_U0_ap_idle;
    sc_signal< sc_logic > read_data_U0_ap_ready;
    sc_signal< sc_lv<6> > read_data_U0_input_r_address0;
    sc_signal< sc_logic > read_data_U0_input_r_ce0;
    sc_signal< sc_lv<16> > read_data_U0_input_r_q0;
    sc_signal< sc_lv<6> > read_data_U0_buf_r_address0;
    sc_signal< sc_logic > read_data_U0_buf_r_ce0;
    sc_signal< sc_logic > read_data_U0_buf_r_we0;
    sc_signal< sc_lv<16> > read_data_U0_buf_r_d0;
    sc_signal< sc_logic > ap_chn_write_read_data_U0_buf_2d_in;
    sc_signal< sc_logic > read_data_U0_buf_r_pipo_status;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_ap_start;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_ap_done;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_ap_continue;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_ap_idle;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_ap_ready;
    sc_signal< sc_lv<6> > dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_address0;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_ce0;
    sc_signal< sc_lv<16> > dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_q0;
    sc_signal< sc_lv<6> > dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_address1;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_ce1;
    sc_signal< sc_lv<16> > dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_q1;
    sc_signal< sc_lv<6> > dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_address0;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_ce0;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_we0;
    sc_signal< sc_lv<16> > dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_d0;
    sc_signal< sc_logic > ap_chn_write_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf;
    sc_signal< sc_logic > dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_pipo_status;
    sc_signal< sc_logic > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start;
    sc_signal< sc_logic > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done;
    sc_signal< sc_logic > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue;
    sc_signal< sc_logic > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_idle;
    sc_signal< sc_logic > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready;
    sc_signal< sc_lv<6> > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_address0;
    sc_signal< sc_logic > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_ce0;
    sc_signal< sc_lv<16> > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_q0;
    sc_signal< sc_lv<6> > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_address0;
    sc_signal< sc_logic > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_ce0;
    sc_signal< sc_logic > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_we0;
    sc_signal< sc_lv<16> > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_d0;
    sc_signal< sc_logic > ap_chn_write_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf;
    sc_signal< sc_logic > dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_pipo_status;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_ap_start;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_ap_done;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_ap_continue;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_ap_idle;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_ap_ready;
    sc_signal< sc_lv<6> > dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_address0;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_ce0;
    sc_signal< sc_lv<16> > dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_q0;
    sc_signal< sc_lv<6> > dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_address1;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_ce1;
    sc_signal< sc_lv<16> > dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_q1;
    sc_signal< sc_lv<6> > dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_address0;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_ce0;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_we0;
    sc_signal< sc_lv<16> > dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_d0;
    sc_signal< sc_logic > ap_chn_write_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf;
    sc_signal< sc_logic > dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_pipo_status;
    sc_signal< sc_logic > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start;
    sc_signal< sc_logic > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done;
    sc_signal< sc_logic > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue;
    sc_signal< sc_logic > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_idle;
    sc_signal< sc_logic > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready;
    sc_signal< sc_lv<6> > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_address0;
    sc_signal< sc_logic > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_ce0;
    sc_signal< sc_lv<16> > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_q0;
    sc_signal< sc_lv<6> > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_address0;
    sc_signal< sc_logic > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_ce0;
    sc_signal< sc_logic > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_we0;
    sc_signal< sc_lv<16> > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_d0;
    sc_signal< sc_logic > ap_chn_write_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out;
    sc_signal< sc_logic > dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_pipo_status;
    sc_signal< sc_logic > write_data_U0_ap_start;
    sc_signal< sc_logic > write_data_U0_ap_done;
    sc_signal< sc_logic > write_data_U0_ap_continue;
    sc_signal< sc_logic > write_data_U0_ap_idle;
    sc_signal< sc_logic > write_data_U0_ap_ready;
    sc_signal< sc_lv<6> > write_data_U0_buf_r_address0;
    sc_signal< sc_logic > write_data_U0_buf_r_ce0;
    sc_signal< sc_lv<16> > write_data_U0_buf_r_q0;
    sc_signal< sc_lv<6> > write_data_U0_output_r_address0;
    sc_signal< sc_logic > write_data_U0_output_r_ce0;
    sc_signal< sc_logic > write_data_U0_output_r_we0;
    sc_signal< sc_lv<16> > write_data_U0_output_r_d0;
    sc_signal< sc_logic > ap_sig_hs_continue;
    sc_signal< sc_lv<6> > buf_2d_in_i_address0;
    sc_signal< sc_logic > buf_2d_in_i_ce0;
    sc_signal< sc_logic > buf_2d_in_i_we0;
    sc_signal< sc_lv<16> > buf_2d_in_i_d0;
    sc_signal< sc_lv<16> > buf_2d_in_i_q0;
    sc_signal< sc_lv<6> > buf_2d_in_i_address1;
    sc_signal< sc_logic > buf_2d_in_i_ce1;
    sc_signal< sc_lv<16> > buf_2d_in_i_q1;
    sc_signal< sc_lv<6> > buf_2d_in_t_address0;
    sc_signal< sc_logic > buf_2d_in_t_ce0;
    sc_signal< sc_logic > buf_2d_in_t_we0;
    sc_signal< sc_lv<16> > buf_2d_in_t_d0;
    sc_signal< sc_lv<16> > buf_2d_in_t_q0;
    sc_signal< sc_lv<6> > buf_2d_in_t_address1;
    sc_signal< sc_logic > buf_2d_in_t_ce1;
    sc_signal< sc_lv<16> > buf_2d_in_t_q1;
    sc_signal< sc_logic > buf_2d_in_U_ap_dummy_ce;
    sc_signal< sc_logic > buf_2d_in_i_full_n;
    sc_signal< sc_logic > buf_2d_in_i_write;
    sc_signal< sc_logic > buf_2d_in_t_empty_n;
    sc_signal< sc_logic > buf_2d_in_t_read;
    sc_signal< sc_lv<6> > row_outbuf_i_address0;
    sc_signal< sc_logic > row_outbuf_i_ce0;
    sc_signal< sc_logic > row_outbuf_i_we0;
    sc_signal< sc_lv<16> > row_outbuf_i_d0;
    sc_signal< sc_lv<16> > row_outbuf_i_q0;
    sc_signal< sc_lv<6> > row_outbuf_t_address0;
    sc_signal< sc_logic > row_outbuf_t_ce0;
    sc_signal< sc_logic > row_outbuf_t_we0;
    sc_signal< sc_lv<16> > row_outbuf_t_d0;
    sc_signal< sc_lv<16> > row_outbuf_t_q0;
    sc_signal< sc_logic > row_outbuf_U_ap_dummy_ce;
    sc_signal< sc_logic > row_outbuf_i_full_n;
    sc_signal< sc_logic > row_outbuf_i_write;
    sc_signal< sc_logic > row_outbuf_t_empty_n;
    sc_signal< sc_logic > row_outbuf_t_read;
    sc_signal< sc_lv<6> > col_inbuf_i_address0;
    sc_signal< sc_logic > col_inbuf_i_ce0;
    sc_signal< sc_logic > col_inbuf_i_we0;
    sc_signal< sc_lv<16> > col_inbuf_i_d0;
    sc_signal< sc_lv<16> > col_inbuf_i_q0;
    sc_signal< sc_lv<6> > col_inbuf_i_address1;
    sc_signal< sc_logic > col_inbuf_i_ce1;
    sc_signal< sc_lv<16> > col_inbuf_i_q1;
    sc_signal< sc_lv<6> > col_inbuf_t_address0;
    sc_signal< sc_logic > col_inbuf_t_ce0;
    sc_signal< sc_logic > col_inbuf_t_we0;
    sc_signal< sc_lv<16> > col_inbuf_t_d0;
    sc_signal< sc_lv<16> > col_inbuf_t_q0;
    sc_signal< sc_lv<6> > col_inbuf_t_address1;
    sc_signal< sc_logic > col_inbuf_t_ce1;
    sc_signal< sc_lv<16> > col_inbuf_t_q1;
    sc_signal< sc_logic > col_inbuf_U_ap_dummy_ce;
    sc_signal< sc_logic > col_inbuf_i_full_n;
    sc_signal< sc_logic > col_inbuf_i_write;
    sc_signal< sc_logic > col_inbuf_t_empty_n;
    sc_signal< sc_logic > col_inbuf_t_read;
    sc_signal< sc_lv<6> > col_outbuf_i_address0;
    sc_signal< sc_logic > col_outbuf_i_ce0;
    sc_signal< sc_logic > col_outbuf_i_we0;
    sc_signal< sc_lv<16> > col_outbuf_i_d0;
    sc_signal< sc_lv<16> > col_outbuf_i_q0;
    sc_signal< sc_lv<6> > col_outbuf_t_address0;
    sc_signal< sc_logic > col_outbuf_t_ce0;
    sc_signal< sc_logic > col_outbuf_t_we0;
    sc_signal< sc_lv<16> > col_outbuf_t_d0;
    sc_signal< sc_lv<16> > col_outbuf_t_q0;
    sc_signal< sc_logic > col_outbuf_U_ap_dummy_ce;
    sc_signal< sc_logic > col_outbuf_i_full_n;
    sc_signal< sc_logic > col_outbuf_i_write;
    sc_signal< sc_logic > col_outbuf_t_empty_n;
    sc_signal< sc_logic > col_outbuf_t_read;
    sc_signal< sc_lv<6> > buf_2d_out_i_address0;
    sc_signal< sc_logic > buf_2d_out_i_ce0;
    sc_signal< sc_logic > buf_2d_out_i_we0;
    sc_signal< sc_lv<16> > buf_2d_out_i_d0;
    sc_signal< sc_lv<16> > buf_2d_out_i_q0;
    sc_signal< sc_lv<6> > buf_2d_out_t_address0;
    sc_signal< sc_logic > buf_2d_out_t_ce0;
    sc_signal< sc_logic > buf_2d_out_t_we0;
    sc_signal< sc_lv<16> > buf_2d_out_t_d0;
    sc_signal< sc_lv<16> > buf_2d_out_t_q0;
    sc_signal< sc_logic > buf_2d_out_U_ap_dummy_ce;
    sc_signal< sc_logic > buf_2d_out_i_full_n;
    sc_signal< sc_logic > buf_2d_out_i_write;
    sc_signal< sc_logic > buf_2d_out_t_empty_n;
    sc_signal< sc_logic > buf_2d_out_t_read;
    sc_signal< sc_logic > ap_reg_procdone_read_data_U0;
    sc_signal< sc_logic > ap_sig_hs_done;
    sc_signal< sc_logic > ap_reg_procdone_dct_Loop_Row_DCT_Loop_proc_U0;
    sc_signal< sc_logic > ap_reg_procdone_dct_Loop_Xpose_Row_Outer_Loop_proc_U0;
    sc_signal< sc_logic > ap_reg_procdone_dct_Loop_Col_DCT_Loop_proc_U0;
    sc_signal< sc_logic > ap_reg_procdone_dct_Loop_Xpose_Col_Outer_Loop_proc_U0;
    sc_signal< sc_logic > ap_reg_procdone_write_data_U0;
    sc_signal< sc_logic > ap_CS;
    sc_signal< sc_logic > ap_sig_top_allready;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_logic ap_const_logic_1;
    static const bool ap_true;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_chn_write_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf();
    void thread_ap_chn_write_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf();
    void thread_ap_chn_write_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out();
    void thread_ap_chn_write_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf();
    void thread_ap_chn_write_read_data_U0_buf_2d_in();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_hs_continue();
    void thread_ap_sig_hs_done();
    void thread_ap_sig_top_allready();
    void thread_buf_2d_in_U_ap_dummy_ce();
    void thread_buf_2d_in_i_address0();
    void thread_buf_2d_in_i_ce0();
    void thread_buf_2d_in_i_d0();
    void thread_buf_2d_in_i_we0();
    void thread_buf_2d_in_i_write();
    void thread_buf_2d_in_t_address0();
    void thread_buf_2d_in_t_address1();
    void thread_buf_2d_in_t_ce0();
    void thread_buf_2d_in_t_ce1();
    void thread_buf_2d_in_t_read();
    void thread_buf_2d_out_U_ap_dummy_ce();
    void thread_buf_2d_out_i_address0();
    void thread_buf_2d_out_i_ce0();
    void thread_buf_2d_out_i_d0();
    void thread_buf_2d_out_i_we0();
    void thread_buf_2d_out_i_write();
    void thread_buf_2d_out_t_address0();
    void thread_buf_2d_out_t_ce0();
    void thread_buf_2d_out_t_read();
    void thread_col_inbuf_U_ap_dummy_ce();
    void thread_col_inbuf_i_address0();
    void thread_col_inbuf_i_ce0();
    void thread_col_inbuf_i_d0();
    void thread_col_inbuf_i_we0();
    void thread_col_inbuf_i_write();
    void thread_col_inbuf_t_address0();
    void thread_col_inbuf_t_address1();
    void thread_col_inbuf_t_ce0();
    void thread_col_inbuf_t_ce1();
    void thread_col_inbuf_t_read();
    void thread_col_outbuf_U_ap_dummy_ce();
    void thread_col_outbuf_i_address0();
    void thread_col_outbuf_i_ce0();
    void thread_col_outbuf_i_d0();
    void thread_col_outbuf_i_we0();
    void thread_col_outbuf_i_write();
    void thread_col_outbuf_t_address0();
    void thread_col_outbuf_t_ce0();
    void thread_col_outbuf_t_read();
    void thread_dct_Loop_Col_DCT_Loop_proc_U0_ap_continue();
    void thread_dct_Loop_Col_DCT_Loop_proc_U0_ap_start();
    void thread_dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_q0();
    void thread_dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_q1();
    void thread_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_pipo_status();
    void thread_dct_Loop_Row_DCT_Loop_proc_U0_ap_continue();
    void thread_dct_Loop_Row_DCT_Loop_proc_U0_ap_start();
    void thread_dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_q0();
    void thread_dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_q1();
    void thread_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_pipo_status();
    void thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue();
    void thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start();
    void thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_pipo_status();
    void thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_q0();
    void thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue();
    void thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start();
    void thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_pipo_status();
    void thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_q0();
    void thread_input_r_address0();
    void thread_input_r_address1();
    void thread_input_r_ce0();
    void thread_input_r_ce1();
    void thread_input_r_d0();
    void thread_input_r_d1();
    void thread_input_r_we0();
    void thread_input_r_we1();
    void thread_output_r_address0();
    void thread_output_r_address1();
    void thread_output_r_ce0();
    void thread_output_r_ce1();
    void thread_output_r_d0();
    void thread_output_r_d1();
    void thread_output_r_we0();
    void thread_output_r_we1();
    void thread_read_data_U0_ap_continue();
    void thread_read_data_U0_ap_start();
    void thread_read_data_U0_buf_r_pipo_status();
    void thread_read_data_U0_input_r_q0();
    void thread_row_outbuf_U_ap_dummy_ce();
    void thread_row_outbuf_i_address0();
    void thread_row_outbuf_i_ce0();
    void thread_row_outbuf_i_d0();
    void thread_row_outbuf_i_we0();
    void thread_row_outbuf_i_write();
    void thread_row_outbuf_t_address0();
    void thread_row_outbuf_t_ce0();
    void thread_row_outbuf_t_read();
    void thread_write_data_U0_ap_continue();
    void thread_write_data_U0_ap_start();
    void thread_write_data_U0_buf_r_q0();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
