// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "dct_Loop_Col_DCT_Loop_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dct_Loop_Col_DCT_Loop_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dct_Loop_Col_DCT_Loop_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_ST_st1_fsm_0 = "000";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_ST_pp0_stg0_fsm_1 = "1";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_ST_pp0_stg1_fsm_2 = "10";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_ST_pp0_stg2_fsm_3 = "11";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_ST_pp0_stg3_fsm_4 = "100";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_ST_st10_fsm_5 = "101";
const sc_lv<1> dct_Loop_Col_DCT_Loop_proc::ap_const_lv1_0 = "0";
const sc_lv<7> dct_Loop_Col_DCT_Loop_proc::ap_const_lv7_0 = "0000000";
const sc_lv<4> dct_Loop_Col_DCT_Loop_proc::ap_const_lv4_0 = "0000";
const sc_lv<7> dct_Loop_Col_DCT_Loop_proc::ap_const_lv7_40 = "1000000";
const sc_lv<7> dct_Loop_Col_DCT_Loop_proc::ap_const_lv7_1 = "1";
const sc_lv<4> dct_Loop_Col_DCT_Loop_proc::ap_const_lv4_8 = "1000";
const sc_lv<4> dct_Loop_Col_DCT_Loop_proc::ap_const_lv4_1 = "1";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_const_lv3_0 = "000";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_const_lv3_1 = "1";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_const_lv3_2 = "10";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_const_lv3_3 = "11";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_const_lv3_4 = "100";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_const_lv3_5 = "101";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_const_lv3_6 = "110";
const sc_lv<3> dct_Loop_Col_DCT_Loop_proc::ap_const_lv3_7 = "111";
const sc_lv<29> dct_Loop_Col_DCT_Loop_proc::ap_const_lv29_1000 = "1000000000000";
const sc_lv<32> dct_Loop_Col_DCT_Loop_proc::ap_const_lv32_D = "1101";
const sc_lv<32> dct_Loop_Col_DCT_Loop_proc::ap_const_lv32_1C = "11100";

dct_Loop_Col_DCT_Loop_proc::dct_Loop_Col_DCT_Loop_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dct_coeff_table_0_U = new dct_Loop_Row_DCT_Loop_proc_dct_coeff_table_0("dct_coeff_table_0_U");
    dct_coeff_table_0_U->clk(ap_clk);
    dct_coeff_table_0_U->reset(ap_rst);
    dct_coeff_table_0_U->address0(dct_coeff_table_0_address0);
    dct_coeff_table_0_U->ce0(dct_coeff_table_0_ce0);
    dct_coeff_table_0_U->q0(dct_coeff_table_0_q0);
    dct_coeff_table_1_U = new dct_Loop_Row_DCT_Loop_proc_dct_coeff_table_1("dct_coeff_table_1_U");
    dct_coeff_table_1_U->clk(ap_clk);
    dct_coeff_table_1_U->reset(ap_rst);
    dct_coeff_table_1_U->address0(dct_coeff_table_1_address0);
    dct_coeff_table_1_U->ce0(dct_coeff_table_1_ce0);
    dct_coeff_table_1_U->q0(dct_coeff_table_1_q0);
    dct_coeff_table_2_U = new dct_Loop_Row_DCT_Loop_proc_dct_coeff_table_2("dct_coeff_table_2_U");
    dct_coeff_table_2_U->clk(ap_clk);
    dct_coeff_table_2_U->reset(ap_rst);
    dct_coeff_table_2_U->address0(dct_coeff_table_2_address0);
    dct_coeff_table_2_U->ce0(dct_coeff_table_2_ce0);
    dct_coeff_table_2_U->q0(dct_coeff_table_2_q0);
    dct_coeff_table_3_U = new dct_Loop_Row_DCT_Loop_proc_dct_coeff_table_3("dct_coeff_table_3_U");
    dct_coeff_table_3_U->clk(ap_clk);
    dct_coeff_table_3_U->reset(ap_rst);
    dct_coeff_table_3_U->address0(dct_coeff_table_3_address0);
    dct_coeff_table_3_U->ce0(dct_coeff_table_3_ce0);
    dct_coeff_table_3_U->q0(dct_coeff_table_3_q0);
    dct_coeff_table_4_U = new dct_Loop_Row_DCT_Loop_proc_dct_coeff_table_4("dct_coeff_table_4_U");
    dct_coeff_table_4_U->clk(ap_clk);
    dct_coeff_table_4_U->reset(ap_rst);
    dct_coeff_table_4_U->address0(dct_coeff_table_4_address0);
    dct_coeff_table_4_U->ce0(dct_coeff_table_4_ce0);
    dct_coeff_table_4_U->q0(dct_coeff_table_4_q0);
    dct_coeff_table_5_U = new dct_Loop_Row_DCT_Loop_proc_dct_coeff_table_5("dct_coeff_table_5_U");
    dct_coeff_table_5_U->clk(ap_clk);
    dct_coeff_table_5_U->reset(ap_rst);
    dct_coeff_table_5_U->address0(dct_coeff_table_5_address0);
    dct_coeff_table_5_U->ce0(dct_coeff_table_5_ce0);
    dct_coeff_table_5_U->q0(dct_coeff_table_5_q0);
    dct_coeff_table_6_U = new dct_Loop_Row_DCT_Loop_proc_dct_coeff_table_6("dct_coeff_table_6_U");
    dct_coeff_table_6_U->clk(ap_clk);
    dct_coeff_table_6_U->reset(ap_rst);
    dct_coeff_table_6_U->address0(dct_coeff_table_6_address0);
    dct_coeff_table_6_U->ce0(dct_coeff_table_6_ce0);
    dct_coeff_table_6_U->q0(dct_coeff_table_6_q0);
    dct_coeff_table_7_U = new dct_Loop_Row_DCT_Loop_proc_dct_coeff_table_7("dct_coeff_table_7_U");
    dct_coeff_table_7_U->clk(ap_clk);
    dct_coeff_table_7_U->reset(ap_rst);
    dct_coeff_table_7_U->address0(dct_coeff_table_7_address0);
    dct_coeff_table_7_U->ce0(dct_coeff_table_7_ce0);
    dct_coeff_table_7_U->q0(dct_coeff_table_7_q0);
    dct_mul_16s_14ns_29_3_U18 = new dct_mul_16s_14ns_29_3<18,3,16,14,29>("dct_mul_16s_14ns_29_3_U18");
    dct_mul_16s_14ns_29_3_U18->clk(ap_clk);
    dct_mul_16s_14ns_29_3_U18->reset(ap_rst);
    dct_mul_16s_14ns_29_3_U18->din0(grp_fu_398_p0);
    dct_mul_16s_14ns_29_3_U18->din1(grp_fu_398_p1);
    dct_mul_16s_14ns_29_3_U18->ce(grp_fu_398_ce);
    dct_mul_16s_14ns_29_3_U18->dout(grp_fu_398_p2);
    dct_mul_16s_15s_29_3_U19 = new dct_mul_16s_15s_29_3<19,3,16,15,29>("dct_mul_16s_15s_29_3_U19");
    dct_mul_16s_15s_29_3_U19->clk(ap_clk);
    dct_mul_16s_15s_29_3_U19->reset(ap_rst);
    dct_mul_16s_15s_29_3_U19->din0(grp_fu_449_p0);
    dct_mul_16s_15s_29_3_U19->din1(grp_fu_449_p1);
    dct_mul_16s_15s_29_3_U19->ce(grp_fu_449_ce);
    dct_mul_16s_15s_29_3_U19->dout(grp_fu_449_p2);
    dct_mul_16s_15s_29_3_U20 = new dct_mul_16s_15s_29_3<20,3,16,15,29>("dct_mul_16s_15s_29_3_U20");
    dct_mul_16s_15s_29_3_U20->clk(ap_clk);
    dct_mul_16s_15s_29_3_U20->reset(ap_rst);
    dct_mul_16s_15s_29_3_U20->din0(grp_fu_499_p0);
    dct_mul_16s_15s_29_3_U20->din1(grp_fu_499_p1);
    dct_mul_16s_15s_29_3_U20->ce(grp_fu_499_ce);
    dct_mul_16s_15s_29_3_U20->dout(grp_fu_499_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_219);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_col_inbuf_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_19_fu_356_p1 );
    sensitive << ( tmp_23_fu_411_p1 );
    sensitive << ( tmp_27_fu_462_p1 );
    sensitive << ( tmp_31_fu_512_p1 );

    SC_METHOD(thread_col_inbuf_address1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_21_fu_369_p1 );
    sensitive << ( tmp_25_fu_423_p1 );
    sensitive << ( tmp_29_fu_474_p1 );
    sensitive << ( tmp_33_fu_524_p1 );

    SC_METHOD(thread_col_inbuf_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( exitcond_flatten_fu_298_p2 );

    SC_METHOD(thread_col_inbuf_ce1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( exitcond_flatten_fu_298_p2 );

    SC_METHOD(thread_col_outbuf_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_34_fu_618_p1 );

    SC_METHOD(thread_col_outbuf_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1 );

    SC_METHOD(thread_col_outbuf_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_2_i_fu_603_p2 );

    SC_METHOD(thread_col_outbuf_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1 );

    SC_METHOD(thread_dct_coeff_table_0_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_i_20_fu_338_p1 );

    SC_METHOD(thread_dct_coeff_table_0_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_fu_298_p2 );

    SC_METHOD(thread_dct_coeff_table_1_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_i_20_fu_338_p1 );

    SC_METHOD(thread_dct_coeff_table_1_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_fu_298_p2 );

    SC_METHOD(thread_dct_coeff_table_2_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_i_20_reg_642 );

    SC_METHOD(thread_dct_coeff_table_2_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_dct_coeff_table_3_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_i_20_reg_642 );

    SC_METHOD(thread_dct_coeff_table_3_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_dct_coeff_table_4_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_i_20_reg_642 );

    SC_METHOD(thread_dct_coeff_table_4_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_dct_coeff_table_5_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_i_20_reg_642 );

    SC_METHOD(thread_dct_coeff_table_5_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_dct_coeff_table_6_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_i_20_reg_642 );

    SC_METHOD(thread_dct_coeff_table_6_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_dct_coeff_table_7_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_i_20_reg_642 );

    SC_METHOD(thread_dct_coeff_table_7_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_exitcond1_i_fu_310_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_fu_298_p2 );
    sensitive << ( k_i_phi_fu_285_p4 );

    SC_METHOD(thread_exitcond_flatten_fu_298_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( indvar_flatten_phi_fu_263_p4 );

    SC_METHOD(thread_grp_fu_398_ce);

    SC_METHOD(thread_grp_fu_398_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( col_inbuf_q0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_grp_fu_398_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( grp_fu_398_p10 );

    SC_METHOD(thread_grp_fu_398_p10);
    sensitive << ( dct_coeff_table_0_q0 );

    SC_METHOD(thread_grp_fu_449_ce);

    SC_METHOD(thread_grp_fu_449_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( col_inbuf_q1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_grp_fu_449_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( dct_coeff_table_3_q0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_grp_fu_499_ce);

    SC_METHOD(thread_grp_fu_499_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( col_inbuf_q1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_grp_fu_499_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( dct_coeff_table_5_load_reg_767 );

    SC_METHOD(thread_i_2_i_mid2_fu_330_p3);
    sensitive << ( i_2_i_phi_fu_274_p4 );
    sensitive << ( exitcond1_i_fu_310_p2 );
    sensitive << ( i_fu_324_p2 );

    SC_METHOD(thread_i_2_i_phi_fu_274_p4);
    sensitive << ( ap_CS_fsm );
    sensitive << ( i_2_i_reg_270 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( i_2_i_mid2_reg_631 );

    SC_METHOD(thread_i_fu_324_p2);
    sensitive << ( i_2_i_phi_fu_274_p4 );

    SC_METHOD(thread_indvar_flatten_next_fu_304_p2);
    sensitive << ( indvar_flatten_phi_fu_263_p4 );

    SC_METHOD(thread_indvar_flatten_phi_fu_263_p4);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar_flatten_reg_259 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( indvar_flatten_next_reg_626 );

    SC_METHOD(thread_k_fu_384_p2);
    sensitive << ( k_i_mid2_fu_316_p3 );

    SC_METHOD(thread_k_i_mid2_fu_316_p3);
    sensitive << ( k_i_phi_fu_285_p4 );
    sensitive << ( exitcond1_i_fu_310_p2 );

    SC_METHOD(thread_k_i_phi_fu_285_p4);
    sensitive << ( ap_CS_fsm );
    sensitive << ( k_i_reg_281 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( k_reg_677 );

    SC_METHOD(thread_p_addr2_fu_378_p2);
    sensitive << ( p_addr_cast_fu_352_p1 );
    sensitive << ( tmp_i_trn_cast_fu_374_p1 );

    SC_METHOD(thread_p_addr_cast_fu_352_p1);
    sensitive << ( tmp_s_fu_344_p3 );

    SC_METHOD(thread_tmp1_fu_529_p2);
    sensitive << ( tmp_8_1_i_reg_737 );
    sensitive << ( grp_fu_398_p2 );

    SC_METHOD(thread_tmp2_fu_560_p2);
    sensitive << ( tmp_8_2_i_reg_787 );
    sensitive << ( grp_fu_449_p2 );

    SC_METHOD(thread_tmp3_fu_598_p2);
    sensitive << ( tmp4_reg_832 );
    sensitive << ( tmp5_fu_594_p2 );

    SC_METHOD(thread_tmp4_fu_583_p2);
    sensitive << ( tmp_8_4_i_reg_817 );
    sensitive << ( grp_fu_499_p2 );

    SC_METHOD(thread_tmp5_fu_594_p2);
    sensitive << ( tmp_8_6_i_reg_822 );
    sensitive << ( tmp6_reg_837 );

    SC_METHOD(thread_tmp6_fu_588_p2);
    sensitive << ( tmp_8_7_i_fu_577_p2 );

    SC_METHOD(thread_tmp_19_fu_356_p1);
    sensitive << ( tmp_s_fu_344_p3 );

    SC_METHOD(thread_tmp_20_fu_361_p3);
    sensitive << ( i_2_i_mid2_fu_330_p3 );

    SC_METHOD(thread_tmp_21_fu_369_p1);
    sensitive << ( tmp_20_fu_361_p3 );

    SC_METHOD(thread_tmp_22_fu_404_p3);
    sensitive << ( i_2_i_mid2_reg_631 );

    SC_METHOD(thread_tmp_23_fu_411_p1);
    sensitive << ( tmp_22_fu_404_p3 );

    SC_METHOD(thread_tmp_24_fu_416_p3);
    sensitive << ( i_2_i_mid2_reg_631 );

    SC_METHOD(thread_tmp_25_fu_423_p1);
    sensitive << ( tmp_24_fu_416_p3 );

    SC_METHOD(thread_tmp_26_fu_455_p3);
    sensitive << ( i_2_i_mid2_reg_631 );

    SC_METHOD(thread_tmp_27_fu_462_p1);
    sensitive << ( tmp_26_fu_455_p3 );

    SC_METHOD(thread_tmp_28_fu_467_p3);
    sensitive << ( i_2_i_mid2_reg_631 );

    SC_METHOD(thread_tmp_29_fu_474_p1);
    sensitive << ( tmp_28_fu_467_p3 );

    SC_METHOD(thread_tmp_2_i_fu_603_p2);
    sensitive << ( tmp_reg_827 );
    sensitive << ( tmp3_reg_842 );

    SC_METHOD(thread_tmp_30_fu_505_p3);
    sensitive << ( i_2_i_mid2_reg_631 );

    SC_METHOD(thread_tmp_31_fu_512_p1);
    sensitive << ( tmp_30_fu_505_p3 );

    SC_METHOD(thread_tmp_32_fu_517_p3);
    sensitive << ( i_2_i_mid2_reg_631 );

    SC_METHOD(thread_tmp_33_fu_524_p1);
    sensitive << ( tmp_32_fu_517_p3 );

    SC_METHOD(thread_tmp_34_fu_618_p1);
    sensitive << ( ap_reg_ppstg_p_addr2_reg_672_pp0_it1 );

    SC_METHOD(thread_tmp_8_1_i_fu_435_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_293 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_tmp_8_1_i_fu_435_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( dct_coeff_table_1_load_reg_692 );

    SC_METHOD(thread_tmp_8_1_i_fu_435_p2);
    sensitive << ( tmp_8_1_i_fu_435_p0 );
    sensitive << ( tmp_8_1_i_fu_435_p1 );

    SC_METHOD(thread_tmp_8_2_i_fu_486_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_293 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_tmp_8_2_i_fu_486_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( dct_coeff_table_2_load_reg_742 );

    SC_METHOD(thread_tmp_8_2_i_fu_486_p2);
    sensitive << ( tmp_8_2_i_fu_486_p0 );
    sensitive << ( tmp_8_2_i_fu_486_p1 );

    SC_METHOD(thread_tmp_8_4_i_fu_541_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_293 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_tmp_8_4_i_fu_541_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( dct_coeff_table_4_load_reg_757 );

    SC_METHOD(thread_tmp_8_4_i_fu_541_p2);
    sensitive << ( tmp_8_4_i_fu_541_p0 );
    sensitive << ( tmp_8_4_i_fu_541_p1 );

    SC_METHOD(thread_tmp_8_6_i_fu_554_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( col_inbuf_q0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_flatten_reg_622 );

    SC_METHOD(thread_tmp_8_6_i_fu_554_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_flatten_reg_622 );
    sensitive << ( dct_coeff_table_6_load_reg_777 );

    SC_METHOD(thread_tmp_8_6_i_fu_554_p2);
    sensitive << ( tmp_8_6_i_fu_554_p0 );
    sensitive << ( tmp_8_6_i_fu_554_p1 );

    SC_METHOD(thread_tmp_8_7_i_fu_577_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_293 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1 );

    SC_METHOD(thread_tmp_8_7_i_fu_577_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1 );
    sensitive << ( dct_coeff_table_7_load_reg_782 );

    SC_METHOD(thread_tmp_8_7_i_fu_577_p2);
    sensitive << ( tmp_8_7_i_fu_577_p0 );
    sensitive << ( tmp_8_7_i_fu_577_p1 );

    SC_METHOD(thread_tmp_fu_565_p2);
    sensitive << ( tmp1_reg_812 );
    sensitive << ( tmp2_fu_560_p2 );

    SC_METHOD(thread_tmp_i_20_fu_338_p1);
    sensitive << ( k_i_mid2_fu_316_p3 );

    SC_METHOD(thread_tmp_i_trn_cast_fu_374_p1);
    sensitive << ( k_i_mid2_fu_316_p3 );

    SC_METHOD(thread_tmp_s_fu_344_p3);
    sensitive << ( i_2_i_mid2_fu_330_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_flatten_fu_298_p2 );
    sensitive << ( ap_sig_bdd_219 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dct_Loop_Col_DCT_Loop_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, col_inbuf_address0, "(port)col_inbuf_address0");
    sc_trace(mVcdFile, col_inbuf_ce0, "(port)col_inbuf_ce0");
    sc_trace(mVcdFile, col_inbuf_q0, "(port)col_inbuf_q0");
    sc_trace(mVcdFile, col_inbuf_address1, "(port)col_inbuf_address1");
    sc_trace(mVcdFile, col_inbuf_ce1, "(port)col_inbuf_ce1");
    sc_trace(mVcdFile, col_inbuf_q1, "(port)col_inbuf_q1");
    sc_trace(mVcdFile, col_outbuf_address0, "(port)col_outbuf_address0");
    sc_trace(mVcdFile, col_outbuf_ce0, "(port)col_outbuf_ce0");
    sc_trace(mVcdFile, col_outbuf_we0, "(port)col_outbuf_we0");
    sc_trace(mVcdFile, col_outbuf_d0, "(port)col_outbuf_d0");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, dct_coeff_table_0_address0, "dct_coeff_table_0_address0");
    sc_trace(mVcdFile, dct_coeff_table_0_ce0, "dct_coeff_table_0_ce0");
    sc_trace(mVcdFile, dct_coeff_table_0_q0, "dct_coeff_table_0_q0");
    sc_trace(mVcdFile, dct_coeff_table_1_address0, "dct_coeff_table_1_address0");
    sc_trace(mVcdFile, dct_coeff_table_1_ce0, "dct_coeff_table_1_ce0");
    sc_trace(mVcdFile, dct_coeff_table_1_q0, "dct_coeff_table_1_q0");
    sc_trace(mVcdFile, dct_coeff_table_2_address0, "dct_coeff_table_2_address0");
    sc_trace(mVcdFile, dct_coeff_table_2_ce0, "dct_coeff_table_2_ce0");
    sc_trace(mVcdFile, dct_coeff_table_2_q0, "dct_coeff_table_2_q0");
    sc_trace(mVcdFile, dct_coeff_table_3_address0, "dct_coeff_table_3_address0");
    sc_trace(mVcdFile, dct_coeff_table_3_ce0, "dct_coeff_table_3_ce0");
    sc_trace(mVcdFile, dct_coeff_table_3_q0, "dct_coeff_table_3_q0");
    sc_trace(mVcdFile, dct_coeff_table_4_address0, "dct_coeff_table_4_address0");
    sc_trace(mVcdFile, dct_coeff_table_4_ce0, "dct_coeff_table_4_ce0");
    sc_trace(mVcdFile, dct_coeff_table_4_q0, "dct_coeff_table_4_q0");
    sc_trace(mVcdFile, dct_coeff_table_5_address0, "dct_coeff_table_5_address0");
    sc_trace(mVcdFile, dct_coeff_table_5_ce0, "dct_coeff_table_5_ce0");
    sc_trace(mVcdFile, dct_coeff_table_5_q0, "dct_coeff_table_5_q0");
    sc_trace(mVcdFile, dct_coeff_table_6_address0, "dct_coeff_table_6_address0");
    sc_trace(mVcdFile, dct_coeff_table_6_ce0, "dct_coeff_table_6_ce0");
    sc_trace(mVcdFile, dct_coeff_table_6_q0, "dct_coeff_table_6_q0");
    sc_trace(mVcdFile, dct_coeff_table_7_address0, "dct_coeff_table_7_address0");
    sc_trace(mVcdFile, dct_coeff_table_7_ce0, "dct_coeff_table_7_ce0");
    sc_trace(mVcdFile, dct_coeff_table_7_q0, "dct_coeff_table_7_q0");
    sc_trace(mVcdFile, indvar_flatten_reg_259, "indvar_flatten_reg_259");
    sc_trace(mVcdFile, i_2_i_reg_270, "i_2_i_reg_270");
    sc_trace(mVcdFile, k_i_reg_281, "k_i_reg_281");
    sc_trace(mVcdFile, reg_293, "reg_293");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, exitcond_flatten_reg_622, "exitcond_flatten_reg_622");
    sc_trace(mVcdFile, exitcond_flatten_fu_298_p2, "exitcond_flatten_fu_298_p2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1, "ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1");
    sc_trace(mVcdFile, indvar_flatten_next_fu_304_p2, "indvar_flatten_next_fu_304_p2");
    sc_trace(mVcdFile, indvar_flatten_next_reg_626, "indvar_flatten_next_reg_626");
    sc_trace(mVcdFile, i_2_i_mid2_fu_330_p3, "i_2_i_mid2_fu_330_p3");
    sc_trace(mVcdFile, i_2_i_mid2_reg_631, "i_2_i_mid2_reg_631");
    sc_trace(mVcdFile, tmp_i_20_fu_338_p1, "tmp_i_20_fu_338_p1");
    sc_trace(mVcdFile, tmp_i_20_reg_642, "tmp_i_20_reg_642");
    sc_trace(mVcdFile, p_addr2_fu_378_p2, "p_addr2_fu_378_p2");
    sc_trace(mVcdFile, p_addr2_reg_672, "p_addr2_reg_672");
    sc_trace(mVcdFile, ap_reg_ppstg_p_addr2_reg_672_pp0_it1, "ap_reg_ppstg_p_addr2_reg_672_pp0_it1");
    sc_trace(mVcdFile, k_fu_384_p2, "k_fu_384_p2");
    sc_trace(mVcdFile, k_reg_677, "k_reg_677");
    sc_trace(mVcdFile, dct_coeff_table_1_load_reg_692, "dct_coeff_table_1_load_reg_692");
    sc_trace(mVcdFile, tmp_8_1_i_fu_435_p2, "tmp_8_1_i_fu_435_p2");
    sc_trace(mVcdFile, tmp_8_1_i_reg_737, "tmp_8_1_i_reg_737");
    sc_trace(mVcdFile, dct_coeff_table_2_load_reg_742, "dct_coeff_table_2_load_reg_742");
    sc_trace(mVcdFile, dct_coeff_table_4_load_reg_757, "dct_coeff_table_4_load_reg_757");
    sc_trace(mVcdFile, dct_coeff_table_5_load_reg_767, "dct_coeff_table_5_load_reg_767");
    sc_trace(mVcdFile, dct_coeff_table_6_load_reg_777, "dct_coeff_table_6_load_reg_777");
    sc_trace(mVcdFile, dct_coeff_table_7_load_reg_782, "dct_coeff_table_7_load_reg_782");
    sc_trace(mVcdFile, tmp_8_2_i_fu_486_p2, "tmp_8_2_i_fu_486_p2");
    sc_trace(mVcdFile, tmp_8_2_i_reg_787, "tmp_8_2_i_reg_787");
    sc_trace(mVcdFile, tmp1_fu_529_p2, "tmp1_fu_529_p2");
    sc_trace(mVcdFile, tmp1_reg_812, "tmp1_reg_812");
    sc_trace(mVcdFile, tmp_8_4_i_fu_541_p2, "tmp_8_4_i_fu_541_p2");
    sc_trace(mVcdFile, tmp_8_4_i_reg_817, "tmp_8_4_i_reg_817");
    sc_trace(mVcdFile, tmp_8_6_i_fu_554_p2, "tmp_8_6_i_fu_554_p2");
    sc_trace(mVcdFile, tmp_8_6_i_reg_822, "tmp_8_6_i_reg_822");
    sc_trace(mVcdFile, tmp_fu_565_p2, "tmp_fu_565_p2");
    sc_trace(mVcdFile, tmp_reg_827, "tmp_reg_827");
    sc_trace(mVcdFile, tmp4_fu_583_p2, "tmp4_fu_583_p2");
    sc_trace(mVcdFile, tmp4_reg_832, "tmp4_reg_832");
    sc_trace(mVcdFile, tmp6_fu_588_p2, "tmp6_fu_588_p2");
    sc_trace(mVcdFile, tmp6_reg_837, "tmp6_reg_837");
    sc_trace(mVcdFile, tmp3_fu_598_p2, "tmp3_fu_598_p2");
    sc_trace(mVcdFile, tmp3_reg_842, "tmp3_reg_842");
    sc_trace(mVcdFile, ap_sig_bdd_219, "ap_sig_bdd_219");
    sc_trace(mVcdFile, indvar_flatten_phi_fu_263_p4, "indvar_flatten_phi_fu_263_p4");
    sc_trace(mVcdFile, i_2_i_phi_fu_274_p4, "i_2_i_phi_fu_274_p4");
    sc_trace(mVcdFile, k_i_phi_fu_285_p4, "k_i_phi_fu_285_p4");
    sc_trace(mVcdFile, tmp_19_fu_356_p1, "tmp_19_fu_356_p1");
    sc_trace(mVcdFile, tmp_21_fu_369_p1, "tmp_21_fu_369_p1");
    sc_trace(mVcdFile, tmp_23_fu_411_p1, "tmp_23_fu_411_p1");
    sc_trace(mVcdFile, tmp_25_fu_423_p1, "tmp_25_fu_423_p1");
    sc_trace(mVcdFile, tmp_27_fu_462_p1, "tmp_27_fu_462_p1");
    sc_trace(mVcdFile, tmp_29_fu_474_p1, "tmp_29_fu_474_p1");
    sc_trace(mVcdFile, tmp_31_fu_512_p1, "tmp_31_fu_512_p1");
    sc_trace(mVcdFile, tmp_33_fu_524_p1, "tmp_33_fu_524_p1");
    sc_trace(mVcdFile, tmp_34_fu_618_p1, "tmp_34_fu_618_p1");
    sc_trace(mVcdFile, exitcond1_i_fu_310_p2, "exitcond1_i_fu_310_p2");
    sc_trace(mVcdFile, i_fu_324_p2, "i_fu_324_p2");
    sc_trace(mVcdFile, k_i_mid2_fu_316_p3, "k_i_mid2_fu_316_p3");
    sc_trace(mVcdFile, tmp_s_fu_344_p3, "tmp_s_fu_344_p3");
    sc_trace(mVcdFile, tmp_20_fu_361_p3, "tmp_20_fu_361_p3");
    sc_trace(mVcdFile, p_addr_cast_fu_352_p1, "p_addr_cast_fu_352_p1");
    sc_trace(mVcdFile, tmp_i_trn_cast_fu_374_p1, "tmp_i_trn_cast_fu_374_p1");
    sc_trace(mVcdFile, grp_fu_398_p0, "grp_fu_398_p0");
    sc_trace(mVcdFile, grp_fu_398_p1, "grp_fu_398_p1");
    sc_trace(mVcdFile, tmp_22_fu_404_p3, "tmp_22_fu_404_p3");
    sc_trace(mVcdFile, tmp_24_fu_416_p3, "tmp_24_fu_416_p3");
    sc_trace(mVcdFile, tmp_8_1_i_fu_435_p0, "tmp_8_1_i_fu_435_p0");
    sc_trace(mVcdFile, tmp_8_1_i_fu_435_p1, "tmp_8_1_i_fu_435_p1");
    sc_trace(mVcdFile, grp_fu_449_p0, "grp_fu_449_p0");
    sc_trace(mVcdFile, grp_fu_449_p1, "grp_fu_449_p1");
    sc_trace(mVcdFile, tmp_26_fu_455_p3, "tmp_26_fu_455_p3");
    sc_trace(mVcdFile, tmp_28_fu_467_p3, "tmp_28_fu_467_p3");
    sc_trace(mVcdFile, tmp_8_2_i_fu_486_p0, "tmp_8_2_i_fu_486_p0");
    sc_trace(mVcdFile, tmp_8_2_i_fu_486_p1, "tmp_8_2_i_fu_486_p1");
    sc_trace(mVcdFile, grp_fu_499_p0, "grp_fu_499_p0");
    sc_trace(mVcdFile, grp_fu_499_p1, "grp_fu_499_p1");
    sc_trace(mVcdFile, tmp_30_fu_505_p3, "tmp_30_fu_505_p3");
    sc_trace(mVcdFile, tmp_32_fu_517_p3, "tmp_32_fu_517_p3");
    sc_trace(mVcdFile, grp_fu_398_p2, "grp_fu_398_p2");
    sc_trace(mVcdFile, tmp_8_4_i_fu_541_p0, "tmp_8_4_i_fu_541_p0");
    sc_trace(mVcdFile, tmp_8_4_i_fu_541_p1, "tmp_8_4_i_fu_541_p1");
    sc_trace(mVcdFile, tmp_8_6_i_fu_554_p0, "tmp_8_6_i_fu_554_p0");
    sc_trace(mVcdFile, tmp_8_6_i_fu_554_p1, "tmp_8_6_i_fu_554_p1");
    sc_trace(mVcdFile, grp_fu_449_p2, "grp_fu_449_p2");
    sc_trace(mVcdFile, tmp2_fu_560_p2, "tmp2_fu_560_p2");
    sc_trace(mVcdFile, tmp_8_7_i_fu_577_p0, "tmp_8_7_i_fu_577_p0");
    sc_trace(mVcdFile, tmp_8_7_i_fu_577_p1, "tmp_8_7_i_fu_577_p1");
    sc_trace(mVcdFile, grp_fu_499_p2, "grp_fu_499_p2");
    sc_trace(mVcdFile, tmp_8_7_i_fu_577_p2, "tmp_8_7_i_fu_577_p2");
    sc_trace(mVcdFile, tmp5_fu_594_p2, "tmp5_fu_594_p2");
    sc_trace(mVcdFile, tmp_2_i_fu_603_p2, "tmp_2_i_fu_603_p2");
    sc_trace(mVcdFile, grp_fu_398_ce, "grp_fu_398_ce");
    sc_trace(mVcdFile, grp_fu_449_ce, "grp_fu_449_ce");
    sc_trace(mVcdFile, grp_fu_499_ce, "grp_fu_499_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_398_p10, "grp_fu_398_p10");

    }
}

dct_Loop_Col_DCT_Loop_proc::~dct_Loop_Col_DCT_Loop_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dct_coeff_table_0_U;
    delete dct_coeff_table_1_U;
    delete dct_coeff_table_2_U;
    delete dct_coeff_table_3_U;
    delete dct_coeff_table_4_U;
    delete dct_coeff_table_5_U;
    delete dct_coeff_table_6_U;
    delete dct_coeff_table_7_U;
    delete dct_mul_16s_14ns_29_3_U18;
    delete dct_mul_16s_15s_29_3_U19;
    delete dct_mul_16s_15s_29_3_U20;
}

void dct_Loop_Col_DCT_Loop_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,3,3>(ap_ST_st10_fsm_5, ap_CS_fsm.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_298_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                    !ap_sig_bdd_219.read())) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
             esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                     !ap_sig_bdd_219.read()) || 
                    (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()))) {
        i_2_i_reg_270 = i_2_i_mid2_reg_631.read();
    } else if ((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_219.read())) {
        i_2_i_reg_270 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()))) {
        indvar_flatten_reg_259 = indvar_flatten_next_reg_626.read();
    } else if ((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_219.read())) {
        indvar_flatten_reg_259 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()))) {
        k_i_reg_281 = k_reg_677.read();
    } else if ((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_219.read())) {
        k_i_reg_281 = ap_const_lv4_0;
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(ap_ST_pp0_stg2_fsm_3, ap_CS_fsm.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())))) {
        reg_293 = col_inbuf_q0.read();
    } else if (((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
                 esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read())))) {
        reg_293 = col_inbuf_q1.read();
    }
    if (esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read())) {
        ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1 = exitcond_flatten_reg_622.read();
        ap_reg_ppstg_p_addr2_reg_672_pp0_it1 = p_addr2_reg_672.read();
    }
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0))) {
        dct_coeff_table_1_load_reg_692 = dct_coeff_table_1_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && esl_seteq<1,3,3>(ap_ST_pp0_stg2_fsm_3, ap_CS_fsm.read()))) {
        dct_coeff_table_2_load_reg_742 = dct_coeff_table_2_q0.read();
        dct_coeff_table_4_load_reg_757 = dct_coeff_table_4_q0.read();
        dct_coeff_table_5_load_reg_767 = dct_coeff_table_5_q0.read();
        dct_coeff_table_6_load_reg_777 = dct_coeff_table_6_q0.read();
        dct_coeff_table_7_load_reg_782 = dct_coeff_table_7_q0.read();
        tmp_8_1_i_reg_737 = tmp_8_1_i_fu_435_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()))) {
        exitcond_flatten_reg_622 = exitcond_flatten_fu_298_p2.read();
        indvar_flatten_next_reg_626 = indvar_flatten_next_fu_304_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_298_p2.read()))) {
        i_2_i_mid2_reg_631 = i_2_i_mid2_fu_330_p3.read();
        k_reg_677 = k_fu_384_p2.read();
        p_addr2_reg_672 = p_addr2_fu_378_p2.read();
        tmp_i_20_reg_642 = tmp_i_20_fu_338_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read()))) {
        tmp1_reg_812 = tmp1_fu_529_p2.read();
        tmp_8_2_i_reg_787 = tmp_8_2_i_fu_486_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,3,3>(ap_ST_pp0_stg2_fsm_3, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1.read()))) {
        tmp3_reg_842 = tmp3_fu_598_p2.read();
    }
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1.read()))) {
        tmp4_reg_832 = tmp4_fu_583_p2.read();
        tmp6_reg_837 = tmp6_fu_588_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()))) {
        tmp_8_4_i_reg_817 = tmp_8_4_i_fu_541_p2.read();
        tmp_8_6_i_reg_822 = tmp_8_6_i_fu_554_p2.read();
        tmp_reg_827 = tmp_fu_565_p2.read();
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         esl_seteq<1,3,3>(ap_ST_st10_fsm_5, ap_CS_fsm.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_ap_ready() {
    if (esl_seteq<1,3,3>(ap_ST_st10_fsm_5, ap_CS_fsm.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_ap_sig_bdd_219() {
    ap_sig_bdd_219 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dct_Loop_Col_DCT_Loop_proc::thread_col_inbuf_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            col_inbuf_address0 =  (sc_lv<6>) (tmp_31_fu_512_p1.read());
        } else if (esl_seteq<1,3,3>(ap_ST_pp0_stg2_fsm_3, ap_CS_fsm.read())) {
            col_inbuf_address0 =  (sc_lv<6>) (tmp_27_fu_462_p1.read());
        } else if (esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read())) {
            col_inbuf_address0 =  (sc_lv<6>) (tmp_23_fu_411_p1.read());
        } else if (esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read())) {
            col_inbuf_address0 =  (sc_lv<6>) (tmp_19_fu_356_p1.read());
        } else {
            col_inbuf_address0 = "XXXXXX";
        }
    } else {
        col_inbuf_address0 = "XXXXXX";
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_col_inbuf_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            col_inbuf_address1 =  (sc_lv<6>) (tmp_33_fu_524_p1.read());
        } else if (esl_seteq<1,3,3>(ap_ST_pp0_stg2_fsm_3, ap_CS_fsm.read())) {
            col_inbuf_address1 =  (sc_lv<6>) (tmp_29_fu_474_p1.read());
        } else if (esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read())) {
            col_inbuf_address1 =  (sc_lv<6>) (tmp_25_fu_423_p1.read());
        } else if (esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read())) {
            col_inbuf_address1 =  (sc_lv<6>) (tmp_21_fu_369_p1.read());
        } else {
            col_inbuf_address1 = "XXXXXX";
        }
    } else {
        col_inbuf_address1 = "XXXXXX";
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_col_inbuf_ce0() {
    if (((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(ap_ST_pp0_stg2_fsm_3, ap_CS_fsm.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_298_p2.read())))) {
        col_inbuf_ce0 = ap_const_logic_1;
    } else {
        col_inbuf_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_col_inbuf_ce1() {
    if (((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(ap_ST_pp0_stg2_fsm_3, ap_CS_fsm.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_298_p2.read())))) {
        col_inbuf_ce1 = ap_const_logic_1;
    } else {
        col_inbuf_ce1 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_col_outbuf_address0() {
    col_outbuf_address0 =  (sc_lv<6>) (tmp_34_fu_618_p1.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_col_outbuf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1.read()))) {
        col_outbuf_ce0 = ap_const_logic_1;
    } else {
        col_outbuf_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_col_outbuf_d0() {
    col_outbuf_d0 = tmp_2_i_fu_603_p2.read().range(28, 13);
}

void dct_Loop_Col_DCT_Loop_proc::thread_col_outbuf_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_flatten_reg_622_pp0_it1.read())))) {
        col_outbuf_we0 = ap_const_logic_1;
    } else {
        col_outbuf_we0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_0_address0() {
    dct_coeff_table_0_address0 =  (sc_lv<3>) (tmp_i_20_fu_338_p1.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_298_p2.read()))) {
        dct_coeff_table_0_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_0_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_1_address0() {
    dct_coeff_table_1_address0 =  (sc_lv<3>) (tmp_i_20_fu_338_p1.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_298_p2.read()))) {
        dct_coeff_table_1_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_1_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_2_address0() {
    dct_coeff_table_2_address0 =  (sc_lv<3>) (tmp_i_20_reg_642.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_2_ce0() {
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0))) {
        dct_coeff_table_2_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_2_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_3_address0() {
    dct_coeff_table_3_address0 =  (sc_lv<3>) (tmp_i_20_reg_642.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_3_ce0() {
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0))) {
        dct_coeff_table_3_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_3_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_4_address0() {
    dct_coeff_table_4_address0 =  (sc_lv<3>) (tmp_i_20_reg_642.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_4_ce0() {
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0))) {
        dct_coeff_table_4_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_4_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_5_address0() {
    dct_coeff_table_5_address0 =  (sc_lv<3>) (tmp_i_20_reg_642.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_5_ce0() {
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0))) {
        dct_coeff_table_5_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_5_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_6_address0() {
    dct_coeff_table_6_address0 =  (sc_lv<3>) (tmp_i_20_reg_642.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_6_ce0() {
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0))) {
        dct_coeff_table_6_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_6_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_7_address0() {
    dct_coeff_table_7_address0 =  (sc_lv<3>) (tmp_i_20_reg_642.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_dct_coeff_table_7_ce0() {
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg1_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0))) {
        dct_coeff_table_7_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_7_ce0 = ap_const_logic_0;
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_exitcond1_i_fu_310_p2() {
    exitcond1_i_fu_310_p2 = (!k_i_phi_fu_285_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_i_phi_fu_285_p4.read() == ap_const_lv4_8);
}

void dct_Loop_Col_DCT_Loop_proc::thread_exitcond_flatten_fu_298_p2() {
    exitcond_flatten_fu_298_p2 = (!indvar_flatten_phi_fu_263_p4.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_phi_fu_263_p4.read() == ap_const_lv7_40);
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_398_ce() {
    grp_fu_398_ce = ap_const_logic_1;
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_398_p0() {
    grp_fu_398_p0 = col_inbuf_q0.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_398_p1() {
    grp_fu_398_p1 =  (sc_lv<14>) (grp_fu_398_p10.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_398_p10() {
    grp_fu_398_p10 = esl_zext<29,14>(dct_coeff_table_0_q0.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_449_ce() {
    grp_fu_449_ce = ap_const_logic_1;
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_449_p0() {
    grp_fu_449_p0 = col_inbuf_q1.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_449_p1() {
    grp_fu_449_p1 = dct_coeff_table_3_q0.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_499_ce() {
    grp_fu_499_ce = ap_const_logic_1;
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_499_p0() {
    grp_fu_499_p0 = col_inbuf_q1.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_grp_fu_499_p1() {
    grp_fu_499_p1 = dct_coeff_table_5_load_reg_767.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_i_2_i_mid2_fu_330_p3() {
    i_2_i_mid2_fu_330_p3 = (!exitcond1_i_fu_310_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond1_i_fu_310_p2.read()[0].to_bool())? i_fu_324_p2.read(): i_2_i_phi_fu_274_p4.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_i_2_i_phi_fu_274_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()))) {
        i_2_i_phi_fu_274_p4 = i_2_i_mid2_reg_631.read();
    } else {
        i_2_i_phi_fu_274_p4 = i_2_i_reg_270.read();
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_i_fu_324_p2() {
    i_fu_324_p2 = (!i_2_i_phi_fu_274_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_bigint<4>(i_2_i_phi_fu_274_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_Loop_Col_DCT_Loop_proc::thread_indvar_flatten_next_fu_304_p2() {
    indvar_flatten_next_fu_304_p2 = (!indvar_flatten_phi_fu_263_p4.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_bigint<7>(indvar_flatten_phi_fu_263_p4.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dct_Loop_Col_DCT_Loop_proc::thread_indvar_flatten_phi_fu_263_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()))) {
        indvar_flatten_phi_fu_263_p4 = indvar_flatten_next_reg_626.read();
    } else {
        indvar_flatten_phi_fu_263_p4 = indvar_flatten_reg_259.read();
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_k_fu_384_p2() {
    k_fu_384_p2 = (!k_i_mid2_fu_316_p3.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_bigint<4>(k_i_mid2_fu_316_p3.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_Loop_Col_DCT_Loop_proc::thread_k_i_mid2_fu_316_p3() {
    k_i_mid2_fu_316_p3 = (!exitcond1_i_fu_310_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond1_i_fu_310_p2.read()[0].to_bool())? ap_const_lv4_0: k_i_phi_fu_285_p4.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_k_i_phi_fu_285_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_622.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()))) {
        k_i_phi_fu_285_p4 = k_reg_677.read();
    } else {
        k_i_phi_fu_285_p4 = k_i_reg_281.read();
    }
}

void dct_Loop_Col_DCT_Loop_proc::thread_p_addr2_fu_378_p2() {
    p_addr2_fu_378_p2 = (!p_addr_cast_fu_352_p1.read().is_01() || !tmp_i_trn_cast_fu_374_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(p_addr_cast_fu_352_p1.read()) + sc_biguint<8>(tmp_i_trn_cast_fu_374_p1.read()));
}

void dct_Loop_Col_DCT_Loop_proc::thread_p_addr_cast_fu_352_p1() {
    p_addr_cast_fu_352_p1 = esl_zext<8,7>(tmp_s_fu_344_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp1_fu_529_p2() {
    tmp1_fu_529_p2 = (!tmp_8_1_i_reg_737.read().is_01() || !grp_fu_398_p2.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp_8_1_i_reg_737.read()) + sc_biguint<29>(grp_fu_398_p2.read()));
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp2_fu_560_p2() {
    tmp2_fu_560_p2 = (!tmp_8_2_i_reg_787.read().is_01() || !grp_fu_449_p2.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp_8_2_i_reg_787.read()) + sc_biguint<29>(grp_fu_449_p2.read()));
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp3_fu_598_p2() {
    tmp3_fu_598_p2 = (!tmp5_fu_594_p2.read().is_01() || !tmp4_reg_832.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp5_fu_594_p2.read()) + sc_biguint<29>(tmp4_reg_832.read()));
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp4_fu_583_p2() {
    tmp4_fu_583_p2 = (!tmp_8_4_i_reg_817.read().is_01() || !grp_fu_499_p2.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp_8_4_i_reg_817.read()) + sc_biguint<29>(grp_fu_499_p2.read()));
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp5_fu_594_p2() {
    tmp5_fu_594_p2 = (!tmp6_reg_837.read().is_01() || !tmp_8_6_i_reg_822.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp6_reg_837.read()) + sc_biguint<29>(tmp_8_6_i_reg_822.read()));
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp6_fu_588_p2() {
    tmp6_fu_588_p2 = (!tmp_8_7_i_fu_577_p2.read().is_01() || !ap_const_lv29_1000.is_01())? sc_lv<29>(): (sc_bigint<29>(tmp_8_7_i_fu_577_p2.read()) + sc_biguint<29>(ap_const_lv29_1000));
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_19_fu_356_p1() {
    tmp_19_fu_356_p1 = esl_zext<64,7>(tmp_s_fu_344_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_20_fu_361_p3() {
    tmp_20_fu_361_p3 = esl_concat<4,3>(i_2_i_mid2_fu_330_p3.read(), ap_const_lv3_1);
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_21_fu_369_p1() {
    tmp_21_fu_369_p1 = esl_zext<64,7>(tmp_20_fu_361_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_22_fu_404_p3() {
    tmp_22_fu_404_p3 = esl_concat<4,3>(i_2_i_mid2_reg_631.read(), ap_const_lv3_2);
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_23_fu_411_p1() {
    tmp_23_fu_411_p1 = esl_zext<64,7>(tmp_22_fu_404_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_24_fu_416_p3() {
    tmp_24_fu_416_p3 = esl_concat<4,3>(i_2_i_mid2_reg_631.read(), ap_const_lv3_3);
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_25_fu_423_p1() {
    tmp_25_fu_423_p1 = esl_zext<64,7>(tmp_24_fu_416_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_26_fu_455_p3() {
    tmp_26_fu_455_p3 = esl_concat<4,3>(i_2_i_mid2_reg_631.read(), ap_const_lv3_4);
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_27_fu_462_p1() {
    tmp_27_fu_462_p1 = esl_zext<64,7>(tmp_26_fu_455_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_28_fu_467_p3() {
    tmp_28_fu_467_p3 = esl_concat<4,3>(i_2_i_mid2_reg_631.read(), ap_const_lv3_5);
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_29_fu_474_p1() {
    tmp_29_fu_474_p1 = esl_zext<64,7>(tmp_28_fu_467_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_2_i_fu_603_p2() {
    tmp_2_i_fu_603_p2 = (!tmp3_reg_842.read().is_01() || !tmp_reg_827.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp3_reg_842.read()) + sc_biguint<29>(tmp_reg_827.read()));
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_30_fu_505_p3() {
    tmp_30_fu_505_p3 = esl_concat<4,3>(i_2_i_mid2_reg_631.read(), ap_const_lv3_6);
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_31_fu_512_p1() {
    tmp_31_fu_512_p1 = esl_zext<64,7>(tmp_30_fu_505_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_32_fu_517_p3() {
    tmp_32_fu_517_p3 = esl_concat<4,3>(i_2_i_mid2_reg_631.read(), ap_const_lv3_7);
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_33_fu_524_p1() {
    tmp_33_fu_524_p1 = esl_zext<64,7>(tmp_32_fu_517_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_34_fu_618_p1() {
    tmp_34_fu_618_p1 = esl_zext<64,8>(ap_reg_ppstg_p_addr2_reg_672_pp0_it1.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_1_i_fu_435_p0() {
    tmp_8_1_i_fu_435_p0 = reg_293.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_1_i_fu_435_p1() {
    tmp_8_1_i_fu_435_p1 = dct_coeff_table_1_load_reg_692.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_1_i_fu_435_p2() {
    tmp_8_1_i_fu_435_p2 = (!tmp_8_1_i_fu_435_p0.read().is_01() || !tmp_8_1_i_fu_435_p1.read().is_01())? sc_lv<29>(): sc_bigint<16>(tmp_8_1_i_fu_435_p0.read()) * sc_bigint<15>(tmp_8_1_i_fu_435_p1.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_2_i_fu_486_p0() {
    tmp_8_2_i_fu_486_p0 = reg_293.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_2_i_fu_486_p1() {
    tmp_8_2_i_fu_486_p1 = dct_coeff_table_2_load_reg_742.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_2_i_fu_486_p2() {
    tmp_8_2_i_fu_486_p2 = (!tmp_8_2_i_fu_486_p0.read().is_01() || !tmp_8_2_i_fu_486_p1.read().is_01())? sc_lv<29>(): sc_bigint<16>(tmp_8_2_i_fu_486_p0.read()) * sc_bigint<15>(tmp_8_2_i_fu_486_p1.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_4_i_fu_541_p0() {
    tmp_8_4_i_fu_541_p0 = reg_293.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_4_i_fu_541_p1() {
    tmp_8_4_i_fu_541_p1 = dct_coeff_table_4_load_reg_757.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_4_i_fu_541_p2() {
    tmp_8_4_i_fu_541_p2 = (!tmp_8_4_i_fu_541_p0.read().is_01() || !tmp_8_4_i_fu_541_p1.read().is_01())? sc_lv<29>(): sc_bigint<16>(tmp_8_4_i_fu_541_p0.read()) * sc_bigint<15>(tmp_8_4_i_fu_541_p1.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_6_i_fu_554_p0() {
    tmp_8_6_i_fu_554_p0 = col_inbuf_q0.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_6_i_fu_554_p1() {
    tmp_8_6_i_fu_554_p1 = dct_coeff_table_6_load_reg_777.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_6_i_fu_554_p2() {
    tmp_8_6_i_fu_554_p2 = (!tmp_8_6_i_fu_554_p0.read().is_01() || !tmp_8_6_i_fu_554_p1.read().is_01())? sc_lv<29>(): sc_bigint<16>(tmp_8_6_i_fu_554_p0.read()) * sc_bigint<15>(tmp_8_6_i_fu_554_p1.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_7_i_fu_577_p0() {
    tmp_8_7_i_fu_577_p0 = reg_293.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_7_i_fu_577_p1() {
    tmp_8_7_i_fu_577_p1 = dct_coeff_table_7_load_reg_782.read();
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_8_7_i_fu_577_p2() {
    tmp_8_7_i_fu_577_p2 = (!tmp_8_7_i_fu_577_p0.read().is_01() || !tmp_8_7_i_fu_577_p1.read().is_01())? sc_lv<29>(): sc_bigint<16>(tmp_8_7_i_fu_577_p0.read()) * sc_bigint<15>(tmp_8_7_i_fu_577_p1.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_fu_565_p2() {
    tmp_fu_565_p2 = (!tmp2_fu_560_p2.read().is_01() || !tmp1_reg_812.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp2_fu_560_p2.read()) + sc_biguint<29>(tmp1_reg_812.read()));
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_i_20_fu_338_p1() {
    tmp_i_20_fu_338_p1 = esl_zext<64,4>(k_i_mid2_fu_316_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_i_trn_cast_fu_374_p1() {
    tmp_i_trn_cast_fu_374_p1 = esl_zext<8,4>(k_i_mid2_fu_316_p3.read());
}

void dct_Loop_Col_DCT_Loop_proc::thread_tmp_s_fu_344_p3() {
    tmp_s_fu_344_p3 = esl_concat<4,3>(i_2_i_mid2_fu_330_p3.read(), ap_const_lv3_0);
}

void dct_Loop_Col_DCT_Loop_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!ap_sig_bdd_219.read()) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_298_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st10_fsm_5;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_3;
            break;
        case 3 : 
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_4;
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st10_fsm_5;
            }
            break;
        case 5 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}
}

