## INFO: No CDC present in FILTER_VDMA
## INFO: When C_PRMRY_IS_ACLK_ASYNC = 0, AXI-VDMA MANDATORY REQUIREMENT IS THAT ALL AXI-VDMA CLOCK PORTS MUST BE CONNECTED TO THE SAME CLOCK SOURCE HAVING SAME FREQUENCY i.e. THERE IS ONLY ONE CLOCK-DOMAIN IN THE ENTIRE FILTER_VDMA DESIGN
## INFO: PLEASE ENSURE THIS REQUIREMENT IS MET.
#
#


