// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dct_1d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_address0,
        src_ce0,
        src_q0,
        tmp_1,
        dst_address0,
        dst_ce0,
        dst_we0,
        dst_d0,
        tmp_11
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] src_address0;
output   src_ce0;
input  [15:0] src_q0;
input  [3:0] tmp_1;
output  [5:0] dst_address0;
output   dst_ce0;
output   dst_we0;
output  [15:0] dst_d0;
input  [3:0] tmp_11;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_ce0;
reg dst_ce0;
reg dst_we0;
reg   [1:0] ap_CS_fsm = 2'b00;
wire   [5:0] dct_coeff_table_address0;
reg    dct_coeff_table_ce0;
wire   [14:0] dct_coeff_table_q0;
reg   [3:0] n_reg_114;
reg   [31:0] tmp1_reg_125;
wire   [3:0] k_1_fu_143_p2;
reg   [3:0] k_1_reg_291;
wire   [0:0] exitcond_fu_149_p2;
reg   [0:0] exitcond_reg_296;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_296_pp0_it1;
wire   [3:0] n_1_fu_155_p2;
reg   [14:0] dct_coeff_table_load_reg_315;
reg   [15:0] src_load_reg_320;
wire   [28:0] tmp_6_fu_210_p1;
reg   [28:0] tmp_6_reg_325;
wire   [31:0] tmp_5_fu_230_p2;
wire   [0:0] exitcond1_fu_137_p2;
reg   [3:0] k_reg_102;
wire   [63:0] tmp_12_fu_183_p1;
wire   [63:0] tmp_14_fu_205_p1;
wire   [63:0] tmp_7_fu_273_p1;
wire   [6:0] tmp_10_fu_165_p3;
wire   [7:0] dct_coeff_table_addr6_cast_fu_173_p1;
wire   [7:0] tmp_6_trn5_cast_fu_161_p1;
wire   [7:0] dct_coeff_table_addr7_fu_177_p2;
wire   [6:0] tmp_13_fu_188_p3;
wire   [7:0] p_addr_cast_fu_195_p1;
wire   [7:0] p_addr1_fu_199_p2;
wire   [15:0] tmp_8_fu_220_p0;
wire   [14:0] tmp_8_fu_220_p1;
wire   [30:0] tmp_8_fu_220_p2;
wire   [31:0] tmp_5_fu_230_p0;
wire   [28:0] tmp_2_fu_236_p2;
wire   [6:0] tmp_fu_256_p3;
wire   [7:0] p_addr2_cast_fu_263_p1;
wire   [7:0] tmp_trn_cast_fu_252_p1;
wire   [7:0] p_addr3_fu_267_p2;
reg   [1:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 2'b00;
parameter    ap_ST_st2_fsm_1 = 2'b1;
parameter    ap_ST_pp0_stg0_fsm_2 = 2'b10;
parameter    ap_ST_st6_fsm_3 = 2'b11;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv29_1000 = 29'b1000000000000;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_true = 1'b1;


dct_1d_dct_coeff_table #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
dct_coeff_table_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( dct_coeff_table_address0 ),
    .ce0( dct_coeff_table_ce0 ),
    .q0( dct_coeff_table_q0 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(exitcond_fu_149_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_137_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_137_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_137_p2))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st6_fsm_3 == ap_CS_fsm)) begin
        k_reg_102 <= k_1_reg_291;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        k_reg_102 <= ap_const_lv4_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_149_p2 == ap_const_lv1_0))) begin
        n_reg_114 <= n_1_fu_155_p2;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_137_p2))) begin
        n_reg_114 <= ap_const_lv4_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_296_pp0_it1 == ap_const_lv1_0))) begin
        tmp1_reg_125 <= tmp_5_fu_230_p2;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_137_p2))) begin
        tmp1_reg_125 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm)) begin
        ap_reg_ppstg_exitcond_reg_296_pp0_it1 <= exitcond_reg_296;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_296 == ap_const_lv1_0))) begin
        dct_coeff_table_load_reg_315 <= dct_coeff_table_q0;
        src_load_reg_320 <= src_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        exitcond_reg_296 <= exitcond_fu_149_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        k_1_reg_291 <= k_1_fu_143_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) begin
        tmp_6_reg_325 <= tmp_6_fu_210_p1;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_CS_fsm or exitcond1_fu_137_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_137_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_137_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_137_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// dct_coeff_table_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond_fu_149_p2 or ap_reg_ppiten_pp0_it0)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_149_p2 == ap_const_lv1_0))) begin
        dct_coeff_table_ce0 = ap_const_logic_1;
    end else begin
        dct_coeff_table_ce0 = ap_const_logic_0;
    end
end

/// dst_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st6_fsm_3 == ap_CS_fsm)) begin
        dst_ce0 = ap_const_logic_1;
    end else begin
        dst_ce0 = ap_const_logic_0;
    end
end

/// dst_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st6_fsm_3 == ap_CS_fsm)) begin
        dst_we0 = ap_const_logic_1;
    end else begin
        dst_we0 = ap_const_logic_0;
    end
end

/// src_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond_fu_149_p2 or ap_reg_ppiten_pp0_it0)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_149_p2 == ap_const_lv1_0))) begin
        src_ce0 = ap_const_logic_1;
    end else begin
        src_ce0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or exitcond1_fu_137_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(ap_const_lv1_0 == exitcond1_fu_137_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_pp0_stg0_fsm_2 : 
            if (~((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_3;
            end
        ap_ST_st6_fsm_3 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign dct_coeff_table_addr6_cast_fu_173_p1 = $unsigned(tmp_10_fu_165_p3);
assign dct_coeff_table_addr7_fu_177_p2 = (dct_coeff_table_addr6_cast_fu_173_p1 + tmp_6_trn5_cast_fu_161_p1);
assign dct_coeff_table_address0 = tmp_12_fu_183_p1;
assign dst_address0 = tmp_7_fu_273_p1;
assign dst_d0 = {{tmp_2_fu_236_p2[ap_const_lv32_1C : ap_const_lv32_D]}};
assign exitcond1_fu_137_p2 = (k_reg_102 == ap_const_lv4_8? 1'b1: 1'b0);
assign exitcond_fu_149_p2 = (n_reg_114 == ap_const_lv4_8? 1'b1: 1'b0);
assign k_1_fu_143_p2 = (k_reg_102 + ap_const_lv4_1);
assign n_1_fu_155_p2 = (n_reg_114 + ap_const_lv4_1);
assign p_addr1_fu_199_p2 = (p_addr_cast_fu_195_p1 + tmp_6_trn5_cast_fu_161_p1);
assign p_addr2_cast_fu_263_p1 = $unsigned(tmp_fu_256_p3);
assign p_addr3_fu_267_p2 = (p_addr2_cast_fu_263_p1 + tmp_trn_cast_fu_252_p1);
assign p_addr_cast_fu_195_p1 = $unsigned(tmp_13_fu_188_p3);
assign src_address0 = tmp_14_fu_205_p1;
assign tmp_10_fu_165_p3 = {{k_reg_102}, {ap_const_lv3_0}};
assign tmp_12_fu_183_p1 = $unsigned(dct_coeff_table_addr7_fu_177_p2);
assign tmp_13_fu_188_p3 = {{tmp_1}, {ap_const_lv3_0}};
assign tmp_14_fu_205_p1 = $unsigned(p_addr1_fu_199_p2);
assign tmp_2_fu_236_p2 = (tmp_6_reg_325 + ap_const_lv29_1000);
assign tmp_5_fu_230_p0 = $signed(tmp_8_fu_220_p2);
assign tmp_5_fu_230_p2 = (tmp_5_fu_230_p0 + tmp1_reg_125);
assign tmp_6_fu_210_p1 = tmp1_reg_125[28:0];
assign tmp_6_trn5_cast_fu_161_p1 = $unsigned(n_reg_114);
assign tmp_7_fu_273_p1 = $unsigned(p_addr3_fu_267_p2);
assign tmp_8_fu_220_p0 = src_load_reg_320;
assign tmp_8_fu_220_p1 = dct_coeff_table_load_reg_315;
assign tmp_8_fu_220_p2 = ($signed(tmp_8_fu_220_p0) * $signed(tmp_8_fu_220_p1));
assign tmp_fu_256_p3 = {{tmp_11}, {ap_const_lv3_0}};
assign tmp_trn_cast_fu_252_p1 = $unsigned(k_reg_102);


endmodule //dct_1d

