/*
 * SoCProc_support.c
 *
 *  Created on: Jul 17, 2015
 *      Author: ga38qoh
 */

// NOTE: this would later be generated by the template engine using information from "SoC_config.h", "sw_functions.h"

#include "SoCProc_support.h"
#include <stdlib.h>



void SoCProc_initialize(void(*ptr)(unsigned int)) {
	int delay;
	SoCProc_elements = malloc(sizeof(SoCProc)*NUM_PROCS);
	// NOTE: if ZYNQ-ARM CortexA9 core available in SoC
	SoCProc_elements[0].m_type = ZYNQ_ARM_CORTEX_A9;
	SoCProc_elements[0].m_id = 1;
	SoCProc_elements[0].m_busy = 0;
	SoCProc_elements[0].m_MEM_BASEADDR = 0x10000000;				//NOTE: this would be got from "SoC_config.h"
	ZYNQ_ARM_CORTEX_A9_initialize(ptr, SoCProc_elements[0].m_MEM_BASEADDR);
	for (delay=0; delay<10000; delay++);				// to ensure that the core is properly initialized before moving onto initializing other core (makes sense for similar cores being initialized by same "*_support.h" modules)
	// NOTE: if Xilinx Microblaze 8.5 IP core available in SoC
	SoCProc_elements[1].m_type = XIL_MICROBLAZE_8_5;
	SoCProc_elements[1].m_id = 2;
	SoCProc_elements[1].m_busy = 0;
	SoCProc_elements[1].m_MEM_BASEADDR = 0x20000000;				//NOTE: this would be got from "SoC_config.h"
	XIL_MICROBLAZE_8_5_initialize(ptr);
	for (delay=0; delay<10000; delay++);
}



unsigned char SoCProc_processDataflow() {
	int i;
	for (i=0; i<NUM_PROCS; i++) {
		if (SoCProc_elements[i].m_busy == 0) {
			SoCProc_elements[i].m_busy = 1;
			// NOTE: if ZYNQ-ARM CortexA9 core available in SoC
			if (SoCProc_elements[i].m_type == ZYNQ_ARM_CORTEX_A9) {
				ZYNQ_ARM_CORTEX_A9_process(&SoCProc_elements[i].m_busy, SoCProc_elements[i].m_MEM_BASEADDR);
			}
			// NOTE: if Xilinx Microblaze 8.5 IP core available in SoC
			if (SoCProc_elements[i].m_type == XIL_MICROBLAZE_8_5) {
				XIL_MICROBLAZE_8_5_process(&SoCProc_elements[i].m_busy, SoCProc_elements[i].m_MEM_BASEADDR);
			}
			return 1;
		}
	}

	return 0;
}








