// this is autogenerated by reading in the register information from the IPXact description of the system

#ifndef __ERODEIP_REGMAP_H__
#define __ERODEIP_REGMAP_H__

#include "../../../../common.h"


typedef struct {
	RegType AP_CTRL;
	RegType GIE;
	RegType IER;
	RegType ISR;
	RegType ROWS_DATA;
	RegType COLS_DATA;
} ErodeIP_RegMap;

#endif

