// this is a template file which will be auto-generated by GRIP framework by using the IP-Xact description provided by this IP 
// The IP supplier can then fill in this template to generate his driver targeting a specific platform

// NOTE: for now it is simulated i.e it is a sample representation of the actual template file which doesnt contain all the registers of this IP


#include "ErodeIP_VDMA_Driver_template.h"


ERODEIP_VDMARegMap ERODEIP_VDMAInitMode = {
								.MM2S_DMACR = {.offset = 0x00, .mask = 0x00000000, .value = 0xffffffff},
								//      ...     //  NOTE: not shown here for simplicity
								.S2MM_DMACR = {.offset = 0x30, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_DMASR = {.offset = 0x34, .mask = 0x00000000, .value = 0xffffffff},
								//      ...     //  NOTE: not shown here for simplicity
								.MM2S_VSIZE = {.offset = 0x50, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_HSIZE = {.offset = 0x54, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_FRMDLY_STRIDE  = {.offset = 0x58, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_START_ADDRESS1 = {.offset = 0x5c, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_START_ADDRESS2 = {.offset = 0x60, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_START_ADDRESS3 = {.offset = 0x64, .mask = 0x00000000, .value = 0xffffffff},
								//      ...     //  NOTE: not shown here for simplicity
								.S2MM_VSIZE = {.offset = 0xa0, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_HSIZE = {.offset = 0xa4, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_FRMDLY_STRIDE  = {.offset = 0xa8, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_START_ADDRESS1 = {.offset = 0xac, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_START_ADDRESS2 = {.offset = 0xb0, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_START_ADDRESS3 = {.offset = 0xb4, .mask = 0x00000000, .value = 0xffffffff}
								//      ...     //  NOTE: not shown here for simplicity
							  };


ERODEIP_VDMARegMap ERODEIP_VDMAStartMode = {
								.MM2S_DMACR = {.offset = 0x00, .mask = 0x00000000, .value = 0xffffffff},
								//      ...     //  NOTE: not shown here for simplicity
								.S2MM_DMACR = {.offset = 0x30, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_DMASR = {.offset = 0x34, .mask = 0x00000000, .value = 0xffffffff},
								//      ...     //  NOTE: not shown here for simplicity
								.MM2S_VSIZE = {.offset = 0x50, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_HSIZE = {.offset = 0x54, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_FRMDLY_STRIDE  = {.offset = 0x58, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_START_ADDRESS1 = {.offset = 0x5c, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_START_ADDRESS2 = {.offset = 0x60, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_START_ADDRESS3 = {.offset = 0x64, .mask = 0x00000000, .value = 0xffffffff},
								//      ...     //  NOTE: not shown here for simplicity
								.S2MM_VSIZE = {.offset = 0xa0, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_HSIZE = {.offset = 0xa4, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_FRMDLY_STRIDE  = {.offset = 0xa8, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_START_ADDRESS1 = {.offset = 0xac, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_START_ADDRESS2 = {.offset = 0xb0, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_START_ADDRESS3 = {.offset = 0xb4, .mask = 0x00000000, .value = 0xffffffff}
								//      ...     //  NOTE: not shown here for simplicity
							  };


ERODEIP_VDMARegMap ERODEIP_VDMAStopMode = {
								.MM2S_DMACR = {.offset = 0x00, .mask = 0x00000000, .value = 0xffffffff},
								//      ...     //  NOTE: not shown here for simplicity
								.S2MM_DMACR = {.offset = 0x30, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_DMASR = {.offset = 0x34, .mask = 0x00000000, .value = 0xffffffff},
								//      ...     //  NOTE: not shown here for simplicity
								.MM2S_VSIZE = {.offset = 0x50, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_HSIZE = {.offset = 0x54, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_FRMDLY_STRIDE  = {.offset = 0x58, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_START_ADDRESS1 = {.offset = 0x5c, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_START_ADDRESS2 = {.offset = 0x60, .mask = 0x00000000, .value = 0xffffffff},
								.MM2S_START_ADDRESS3 = {.offset = 0x64, .mask = 0x00000000, .value = 0xffffffff},
								//      ...     //  NOTE: not shown here for simplicity
								.S2MM_VSIZE = {.offset = 0xA0, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_HSIZE = {.offset = 0xA4, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_FRMDLY_STRIDE  = {.offset = 0xA8, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_START_ADDRESS1 = {.offset = 0xAc, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_START_ADDRESS2 = {.offset = 0xB0, .mask = 0x00000000, .value = 0xffffffff},
								.S2MM_START_ADDRESS3 = {.offset = 0xB4, .mask = 0x00000000, .value = 0xffffffff}
								//      ...     //  NOTE: not shown here for simplicity
						      };

// this function wrties to the memory mapped peripheral register @addr
static void localWriteReg(unsigned int addr, unsigned int mask, unsigned int value) {
    // only write to reg if mask != 0
    if ((mask | 0x0) != 0x0) {
        *((volatile unsigned int *)(addr)) = (*(volatile unsigned int *)(addr) & ~(mask)) | value;
    }
}


// this function reads from the memory mapped peripheral register @addr
static unsigned int localReadReg(unsigned int addr) {
    return (unsigned int) *((volatile unsigned int *)(addr));
}


// updates the VDMA IP peripheral's memory mapped registers with content provided in mode 
static void SetHAMode(ERODEIP_VDMARegMap mode, unsigned int baseaddr) {
    localWriteReg(baseaddr + mode.MM2S_DMACR.offset, mode.MM2S_DMACR.mask, mode.MM2S_DMACR.value);
    //      ...     //  NOTE: not shown here for simplicity
    localWriteReg(baseaddr + mode.S2MM_DMACR.offset, mode.S2MM_DMACR.mask, mode.S2MM_DMACR.value);
    localWriteReg(baseaddr + mode.S2MM_DMASR.offset, mode.S2MM_DMASR.mask, mode.S2MM_DMASR.value);
    //      ...     //  NOTE: not shown here for simplicity    
    localWriteReg(baseaddr + mode.MM2S_VSIZE.offset, mode.MM2S_VSIZE.mask, mode.MM2S_VSIZE.value);        
    localWriteReg(baseaddr + mode.MM2S_HSIZE.offset, mode.MM2S_HSIZE.mask, mode.MM2S_HSIZE.value);        
    localWriteReg(baseaddr + mode.MM2S_FRMDLY_STRIDE.offset, mode.MM2S_FRMDLY_STRIDE.mask, mode.MM2S_FRMDLY_STRIDE.value);        
    localWriteReg(baseaddr + mode.MM2S_START_ADDRESS1.offset, mode.MM2S_START_ADDRESS1.mask, mode.MM2S_START_ADDRESS1.value);        
    localWriteReg(baseaddr + mode.MM2S_START_ADDRESS2.offset, mode.MM2S_START_ADDRESS2.mask, mode.MM2S_START_ADDRESS2.value);        
    localWriteReg(baseaddr + mode.MM2S_START_ADDRESS3.offset, mode.MM2S_START_ADDRESS3.mask, mode.MM2S_START_ADDRESS3.value);        
    //      ...     //  NOTE: not shown here for simplicity
    localWriteReg(baseaddr + mode.S2MM_VSIZE.offset, mode.S2MM_VSIZE.mask, mode.S2MM_VSIZE.value);        
    localWriteReg(baseaddr + mode.S2MM_HSIZE.offset, mode.S2MM_HSIZE.mask, mode.S2MM_HSIZE.value);        
    localWriteReg(baseaddr + mode.S2MM_FRMDLY_STRIDE.offset, mode.S2MM_FRMDLY_STRIDE.mask, mode.S2MM_FRMDLY_STRIDE.value);        
    localWriteReg(baseaddr + mode.S2MM_START_ADDRESS1.offset, mode.S2MM_START_ADDRESS1.mask, mode.S2MM_START_ADDRESS1.value);        
    localWriteReg(baseaddr + mode.S2MM_START_ADDRESS2.offset, mode.S2MM_START_ADDRESS2.mask, mode.S2MM_START_ADDRESS2.value);        
    localWriteReg(baseaddr + mode.S2MM_START_ADDRESS3.offset, mode.S2MM_START_ADDRESS3.mask, mode.S2MM_START_ADDRESS3.value);        
    //      ...     //  NOTE: not shown here for simplicity                           
}



// the IP supplier should make necessary modifications to initialize the VDMA IP here
void ERODEIP_VDMA_Driver_initialize(ERODEIP_VDMADriverInstance *InstancePtr) {
	SetHAMode(ERODEIP_VDMAInitMode, InstancePtr->baseaddr);
}


// the IP supplier should make necessary modifications to trigger the VDMA IP to start processing here
void ERODEIP_VDMA_Driver_start(ERODEIP_VDMADriverInstance *InstancePtr) {
    SetHAMode(ERODEIP_VDMAStartMode, InstancePtr->baseaddr);
}


// the IP supplier should make necessary modifications to stop the VDMA IP processing here
void ERODEIP_VDMA_Driver_stop(ERODEIP_VDMADriverInstance *InstancePtr) {
    SetHAMode(ERODEIP_VDMAStopMode, InstancePtr->baseaddr);
}

// the IP supplier should make necessary modifications to inform about the Busy status here
bool ERODEIP_VDMA_Driver_isBusy(ERODEIP_VDMADriverInstance *InstancePtr) {    
    return (bool) ((localReadReg(InstancePtr->baseaddr + ERODEIP_VDMA_BUSY_STATUS_REG_offset) >> ERODEIP_VDMA_BUSY_STATUS_REG_bit) & 1);
}









// NOTE: everything seems to be auto-generatable!!












